'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8');
const context={__ABILITY_TEST__:true,console,setTimeout,clearTimeout,localStorage:{getItem:()=>null,setItem:()=>{}},globalThis:null};
context.globalThis=context;
vm.runInNewContext(source,context,{filename:'app.js'});
const A=context.AbilityCatalog;
const riderNames=['Precognition','Dream Walking','Earth Wielding','Weakness Detection','Water Wielding','Ward Weaving','Underwater Breathing','Truth-Sayer','Storm Wielding','Sound Seeking','Size Changing','Siphoning','Shadow Wielding','Revoking Speech','Retrocognition','Object Summoning','Metallurgy','Mending','Memory Erasure','Lightning Wielding','Inntinnsic','Illusion Crafting','Ice Wielding','Fire Wielding','Farsight','Ward Creation','Distance Wielding','Signet Countering','Battle Foresight','Astral Projection','Air Wielding','Agrarian'];
const flierNames=['Emotion Heightening','Truth-Sayer','Desire Detection','Emotion Sensing','Emotion Siphoning','Emotion Projection','Intent Detection','Mental Shielding','Memory Echo','Thought Projection','Mental Veiling','Fear Projection','Calming Influence','Presence Detection','Bond Reading','Compulsion Resistance','Dream Sending','Sensory Sharing'];
assert.deepEqual(Array.from(A.RIDER_SIGNETS,x=>x.name),riderNames);
assert.deepEqual(Array.from(A.FLIER_GIFTS,x=>x.name),flierNames);
for(const [label,pool,path] of [['Rider',A.RIDER_SIGNETS,'rider'],['Flier',A.FLIER_GIFTS,'gryphon']]){
  assert.equal(new Set(pool.map(x=>x.id)).size,pool.length,`${label} IDs unique`);
  assert.equal(new Set(pool.map(x=>x.name)).size,pool.length,`${label} names unique`);
  pool.forEach(x=>{assert.ok(x.id&&x.name&&x.description&&x.traits.length);assert.ok(x.paths.includes(path));});
}
assert.strictEqual(A.abilityPoolFor('dark'),A.RIDER_SIGNETS);
assert.strictEqual(A.abilityPoolFor('rider'),A.RIDER_SIGNETS);
assert.strictEqual(A.abilityPoolFor('gryphon'),A.FLIER_GIFTS);
for(const elemental of ['Lightning Wielding','Fire Wielding','Earth Wielding','Storm Wielding','Distance Wielding','Metallurgy'])assert.ok(!flierNames.includes(elemental));
const scores={mind:9,empathy:7,control:2};
assert.equal(A.selectAbility(A.FLIER_GIFTS,scores).id,A.selectAbility(A.FLIER_GIFTS,scores).id,'scoring is deterministic');
assert.notEqual(A.selectAbility(A.RIDER_SIGNETS,{power:12}).id,A.selectAbility(A.RIDER_SIGNETS,{mind:12}).id,'different Rider profiles vary');assert.notEqual(A.selectAbility(A.FLIER_GIFTS,{mind:12}).id,A.selectAbility(A.FLIER_GIFTS,{defense:12}).id,'different Flier profiles vary');
const riderResult=A.generateBondResult('rider',scores),flierResult=A.generateBondResult('gryphon',scores),darkResult=A.generateBondResult('dark',scores);assert.ok(riderNames.includes(riderResult.ability));assert.ok(flierNames.includes(flierResult.ability));assert.ok(riderNames.includes(darkResult.ability));assert.ok(darkResult.darkEffect&&darkResult.abilityDesc);
for(const [oldName,newName] of Object.entries({'Truth-Sensing':'Truth-Sayer','Mind Reading':'Inntinnsic','Metal Wielding':'Metallurgy','Sound Wielding':'Sound Seeking'}))assert.equal(A.abilityBySavedValue(oldName,'rider').name,newName);
const legacy={ability:'Thread-Sight',abilityDesc:'Existing description'};A.normalizeBondAbility(legacy,'rider');const once=JSON.stringify(legacy);A.normalizeBondAbility(legacy,'rider');assert.equal(JSON.stringify(legacy),once);assert.equal(legacy.ability,'Thread-Sight');assert.match(legacy.abilityId,/^legacy-/);
const saved={profile:{path:'gryphon',bond:{ability:'Emotion Heightening'}},pathRecords:{rider:{bond:{ability:'Metal Wielding'}},gryphon:{bond:{ability:'Emotion Heightening'}},dark:{bond:{ability:'Shadow Wielding'}}}};
const normalized=A.normalizeState(saved);assert.equal(normalized.abilitySchemaVersion,'schema-v10');assert.equal(normalized.pathRecords.rider.bond.ability,'Metallurgy');assert.equal(normalized.pathRecords.gryphon.bond.ability,'Emotion Heightening');assert.ok(normalized.pathRecords.dark.bond.darkEffect);assert.equal(A.normalizeState(normalized).pathRecords.dark.bond.abilityId,normalized.pathRecords.dark.bond.abilityId);
assert.doesNotMatch(source,/const\s+SIGNETS\s*=/);
for(const typo of ['Intrinsic','Metalurgy','Projectiong'])assert.ok(!riderNames.concat(flierNames).includes(typo));
for(const outdated of ['Dream Walker','Shadow Wielder'])assert.ok(!riderNames.includes(outdated));
console.log(`ability pool assertions passed (${A.RIDER_SIGNETS.length} Rider, ${A.FLIER_GIFTS.length} Flier)`);
