const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const app = fs.readFileSync('app.js', 'utf8');
const features = fs.readFileSync('investigation-features.js', 'utf8');
const css = fs.readFileSync('dossier-experience.css', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
const builder = fs.readFileSync('visual-builder.js', 'utf8');

assert.match(app, /class="book-form-grid"/);
assert.match(app, /class="book-reactions"/);
assert.match(app, /class="reaction-grid"/);
assert.match(app, /class="book-modal-footer"/);
assert.match(builder, /class="visual-book-canvas"/);
assert.match(builder, /data-visual-module/);
assert.match(builder, /data-action="edit-book"/);
assert.match(app, /bookRangeField\('bRating','Overall rating',book.rating,'rating'\)/);
assert.match(app, /data-range-format="percent"/);
assert.match(css, /\.book-metadata\{display:flex;flex-wrap:wrap/);
assert.match(css, /@media\(max-width:650px\)[^{]*\{[^}]*\.library-controls\{grid-template-columns:1fr/);
assert.match(css, /\.book-form-grid,.reaction-grid\{grid-template-columns:1fr\}/);
assert.match(css, /100dvh/);
assert.match(css, /--visual-viewport-height/);
assert.match(css, /\.book-form-body\{[^}]*overflow-y:auto/);
assert.match(css, /\.book-modal-footer\{position:sticky/);
assert.match(css, /input\.shared-range::-webkit-slider-thumb/);
assert.match(css, /input\.shared-range::-moz-range-thumb/);
assert.match(css, /--range-percent/);
assert.match(css, /touch-action:pan-y/);
assert.match(features, /MutationObserver/);
assert.match(features, /rangeEnhanced === 'true'/);
assert.match(features, /addEventListener\('input'/);
assert.match(features, /aria-valuetext/);
assert.strictEqual((html.match(/id="formModal"/g)||[]).length, 1);

const start = features.indexOf('function rangePercent');
const end = features.indexOf('function updateRange', start);
const context = {};
vm.runInNewContext(`${features.slice(start, end)};this.rangePercent=rangePercent;this.formatRangeValue=formatRangeValue`, context);
assert.strictEqual(context.rangePercent(5, 0, 5), 100);
assert.strictEqual(context.rangePercent(3, 1, 5), 50);
assert.strictEqual(context.rangePercent(-2, 0, 5), 0);
assert.strictEqual(context.rangePercent(9, 0, 5), 100);
assert.strictEqual(context.formatRangeValue({value:'4',max:'5',dataset:{rangeFormat:'rating'}}), '4 / 5');
assert.strictEqual(context.formatRangeValue({value:'73',max:'100',dataset:{rangeFormat:'percent'}}), '73%');

const ranges = [...app.matchAll(/<input[^>]+type="range"[^>]*>/g)].map(match => match[0]);
assert.ok(ranges.length >= 3);
ranges.forEach(markup => assert.match(markup, /shared-range/));
console.log('book responsive and shared slider regression tests passed');
