'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('dossier-experience.css','utf8');
const mind=fs.readFileSync('mind-map.js','utf8');
const builder=fs.readFileSync('visual-builder.js','utf8');
const context={__ABILITY_TEST__:true,console,setTimeout,clearTimeout,localStorage:{getItem:()=>null,setItem:()=>{}},globalThis:null};context.globalThis=context;
vm.runInNewContext(source,context,{filename:'app.js'});
const A=context.AbilityCatalog;
const legacy={id:'book-1',title:'Fourth Wing',author:'Rebecca Yarros',series:'The Empyrean',rating:4.5,spice:2.5,impact:5,progress:67,coverUrl:'cover.jpg',notes:['First note'],genre:' Fantasy, fantasy , Romantasy '};
const normalized=A.normalizeState({books:[legacy],bookConnections:[]});
const book=normalized.books[0];
assert.equal(book.id,'book-1');assert.equal(book.rating,4.5);assert.equal(book.spice,2.5);assert.equal(book.progress,67);assert.equal(book.coverUrl,'cover.jpg');
assert.deepEqual(Array.from(book.genres),['Fantasy','Romantasy']);
for(const key of ['summary','about','tags','notes','ratings','linkedDossierIds','linkedTheoryIds','linkedWallIds','images','metadata','createdAt','updatedAt'])assert.ok(Object.hasOwn(book,key),key);
assert.equal(book.notes.length,1);assert.equal(book.notes[0].text,'First note');
const once=JSON.stringify(book);A.normalizeBookRecord(book);assert.equal(JSON.stringify(book),once,'book migration is idempotent');
assert.deepEqual(Array.from(A.normalizeTextList(['Dark  Fantasy','dark fantasy',' Horror '])),['Dark Fantasy','Horror']);
const related={id:'book-2',title:'Iron Flame'};
const stateWithConnections=A.normalizeState({books:[book,related],bookConnections:[{id:'c1',fromBookId:'book-1',toBookId:'book-2',type:'sequel to'},{id:'c2',fromBookId:'book-1',toBookId:'book-2',type:'Sequel To'}]});
assert.equal(stateWithConnections.bookConnections.length,1,'identical canonical relationships deduplicate');
assert.match(source,/data-action="view-book"/);assert.match(source,/'view-book':\(\)=>openBookProfile/);
for(const heading of ['About this book','Ratings','Connections','Dossiers','Theories','Walls','Book relationships','Notes'])assert.ok(source.includes(heading),heading);
assert.match(source,/function openBookNoteEditor/);assert.match(source,/function openBookConnectionEditor/);
assert.match(source,/linkedDossierIds:selectedValues\('bDossiers'\)/);assert.match(source,/linkedTheoryIds:selectedValues\('bTheories'\)/);assert.match(source,/linkedWallIds:selectedValues\('bWalls'\)/);
assert.match(builder,/data-notes-count/);assert.match(builder,/data-theory-count/);assert.match(builder,/data-dossier-count/);assert.match(builder,/data-wall-count/);
assert.match(css,/\.book-profile>header/);assert.match(css,/var\(--ui-surface-raised\)/);assert.match(css,/var\(--ui-accent\)/);assert.match(css,/@media\(max-width:650px\)\{\.book-profile-backdrop/);
assert.match(mind,/function bookGraphRecords/);assert.match(mind,/recordType:'book'/);assert.match(mind,/state\.bookConnections/);
console.log('first-class book archive record assertions passed');
