'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('canvas-editor.js','utf8'),css=fs.readFileSync('visual-builder.css','utf8');
const context={globalThis:null,console,Set,Map,Promise,JSON,Number,String,Math,Date,document:{addEventListener(){}},window:{},Image:function(){}};context.globalThis=context;vm.runInNewContext(source,context);const C=context.CanvasEditor,html=C.editorShell({canvasId:'test-canvas',title:'Test',width:420,height:380});
for(const page of ['templates','elements','text','fields','uploads']){assert.match(html,new RegExp(`role="tab"[^>]+data-fabric-panel-tab="${page}"`));assert.match(html,new RegExp(`role="tabpanel"[^>]+data-fabric-panel="${page}"`));}
assert.equal((html.match(/role="tabpanel"/g)||[]).length,5);assert.equal((html.match(/role="tabpanel"[^>]*hidden/g)||[]).length,4,'only one tool page starts visible');
for(const hook of ['data-fabric-add="text"','data-fabric-text-tools','data-fabric-font-search','data-fabric-font-list','data-fabric-text-preset','data-fabric-element','data-fabric-asset-search','data-fabric-asset-filter','data-fabric-asset-list','data-fabric-card-preset','data-fabric-share-formatting','data-fabric-field','data-fabric-combined-search','data-fabric-combined-type','data-fabric-combined-category','data-fabric-combined-list','data-fabric-zoom','data-fabric-snapping','data-fabric-card-bg','data-fabric-delete'])assert.ok(html.includes(hook),hook);
assert.equal((html.match(/data-fabric-prop="fontSize"/g)||[]).length,1,'font size lives only in Text');for(const retained of ['data-fabric-prop="width"','data-fabric-prop="height"','data-fabric-prop="angle"','data-fabric-prop="opacity"','data-fabric-prop="cornerRadius"','data-fabric-prop="strokeWidth"','data-fabric-layer-list','data-fabric-image-controls','data-fabric-value-controls'])assert.ok(html.includes(retained),retained);
assert.match(source,/ArrowLeft.*ArrowRight.*Home.*End/);assert.match(source,/showPanel\(tab\.dataset\.fabricPanelTab\)/);assert.match(source,/data-fabric-mobile-layout/);assert.match(css,/\.fabric-sidebar-pages\{[^}]*overflow-y:auto/);assert.match(css,/\.fabric-library-grid,.fabric-library-list,.fabric-combined-library\{[^}]*max-height:310px[^}]*overflow-y:auto/);assert.match(css,/data-fabric-mobile-layout=tools/);assert.match(css,/\.fabric-library-choice strong\{[^}]*overflow-wrap:anywhere/);
console.log('Canvas editor tab pages, contained libraries, inspector organization, and responsive view navigation assertions passed');
