'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('visual-builder.js','utf8'),css=fs.readFileSync('visual-builder.css','utf8'),bridge=fs.readFileSync('supabase-bridge.js','utf8');
const state={books:[{id:'book',title:'A Very Long Fourth Wing Archive Title',author:'Rebecca Yarros',series:'The Empyrean',status:'reading',progress:61,rating:4.5,spice:3,impact:5,trackerValues:{}}],sessions:[],visualTemplates:[],visualAssets:[]};
const context={globalThis:null,state,console,Date,Math,Number,String,Boolean,Array,Set,Map,saveState(){},renderAll(){},bookCardStats(){return{notesCount:0,theoryCount:0,dossierCount:0,wallCount:0}}};context.globalThis=context;vm.runInNewContext(source,context);const B=context.VisualBuilder,book=state.books[0];
assert.equal(B.BUILDER_SCHEMA_VERSION,6);assert.equal(B.VISUAL_ASSET_VERSION,'20260802-29');
const decorative=['horizontal-line','vertical-line','divider','rectangle','rounded-rectangle','circle','pill','card-border','background-panel','icon','decorative-text','uploaded-image','transparent-overlay'];for(const type of decorative)assert.ok(B.MODULE_TYPES.includes(type),type);
const template=B.createTemplate({id:'canva',canvas:{width:640,height:900,backgroundColor:'var(--ui-surface, var(--panel))'},modules:[B.createModule('title',{id:'title',x:80,y:100,width:300,height:90,dataBinding:{path:'title'},style:{fontSize:32,autoFit:false,textColor:'#123456',opacity:.8,overflow:'wrap'}}),B.createModule('rectangle',{id:'shape',x:20,y:20,width:200,height:100,style:{fill:'transparent',fillOpacity:.5,borderColor:'#654321'}}),B.createModule('uploaded-image',{id:'asset',x:200,y:300,width:160,height:160,config:{src:'https://example.test/image.webp'},style:{imageFit:'contain',cropX:30,cropY:70,flipX:true}})]});
const before=JSON.parse(JSON.stringify(template));B.resizeModule(template,'title',360,120);assert.equal(template.modules[0].style.fontSize,32,'box resize does not alter explicit font size');assert.equal(template.modules[0].style.autoFit,false);assert.equal(template.modules[0].customWidth,360);assert.equal(template.modules[0].customHeight,120);assert.equal(template.modules[0].style.textColor,'#123456');assert.equal(template.modules[0].style.opacity,.8);
const moduleHtml=B.renderBookModule({...template.modules[2],_canvasWidth:640,_canvasHeight:900},book);assert.match(moduleHtml,/--module-image-fit:contain/);assert.match(moduleHtml,/--module-crop-x:30%/);assert.match(moduleHtml,/--module-flip-x:-1/);
for(const size of ['small','medium','large']){const html=B.renderCard(template,book,{size,device:'mobile'});assert.match(html,new RegExp(`data-card-size="${size}"`));assert.match(html,/data-device="mobile"/);assert.match(html,/--template-ratio:640\/900/);assert.match(html,/--module-x:12\.5%/);assert.match(html,/--module-font-size:5cqw/);}
const production=B.renderCard(template,book,{size:'medium'}),preview=B.renderCard(template,book,{size:'medium'});assert.equal(preview,production,'Preview and production use identical authoritative renderer output');const edit=B.renderCard(template,book,{size:'medium',editor:true});assert.match(edit,/builder-resize-handle is-nw/);assert.match(edit,/builder-rotate-handle/);assert.doesNotMatch(production,/builder-resize-handle|builder-safe-area/);
const migrated=B.normalizeTemplate(before),again=B.normalizeTemplate(JSON.parse(JSON.stringify(migrated)));assert.deepEqual(again,migrated);assert.deepEqual(migrated.modules.map(({id,x,y,width,height,rotation,layer})=>({id,x,y,width,height,rotation,layer})),before.modules.map(({id,x,y,width,height,rotation,layer})=>({id,x,y,width,height,rotation,layer})));
const snap=B.snapModulePosition(B.createTemplate({canvas:{width:640,height:900,grid:8,snap:true},modules:[B.createModule('text',{id:'a',x:0,y:0,width:100,height:50}),B.createModule('text',{id:'b',x:201,y:101,width:100,height:50})]}),{id:'a',width:100,height:50},202,102);assert.ok(snap.guides.length);
for(const hook of ['data-editor-view="edit"','data-editor-view="preview"','data-builder-zoom="out"','data-builder-zoom="in"','data-builder-zoom="fit"','data-builder-zoom="100"','data-style-color','data-inspect-font-size','data-inspect-autofit','data-upload-asset','data-reset-standard','data-layer-select','const action=button.dataset.builderZoom'])assert.ok(source.includes(hook),hook);
assert.doesNotMatch(source,/querySelector\('\[data-builder-zoom-fit\]'\)\.onclick/,'zoom controls do not bind to missing selectors');
assert.match(css,/\.visual-card-viewport/);assert.match(css,/aspect-ratio:var\(--template-ratio\)/);assert.match(css,/\.visual-book-canvas:before/);assert.match(css,/@media\(max-width:650px\)/);assert.match(bridge,/storage\.from\('visual-assets'\)\.upload/);assert.match(bridge,/user\.id/);
console.log('Canva-style authoritative renderer, object styling, uniform scale, decorative assets, draft-safe migration, and cloud upload assertions passed');
