'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('visual-builder.js','utf8'),canvas=fs.readFileSync('canvas-editor.js','utf8'),css=fs.readFileSync('visual-builder.css','utf8');
const state={books:[{id:'legacy-book',title:'Legacy Book',visualTemplateId:'legacy'},{id:'fabric-book',title:'Fabric Book',visualTemplateId:'fabric'},{id:'empty-book',title:'Empty Scene',visualTemplateId:'empty'}],sessions:[],visualTemplates:[]},context={globalThis:null,state,console,Date,Math,Number,String,Boolean,Array,Set,Map,saveState(){},bookCardStats(){return{notesCount:0,theoryCount:0,dossierCount:0,wallCount:0}}};context.globalThis=context;vm.runInNewContext(source,context);const B=context.VisualBuilder;
const legacy=B.createTemplate({id:'legacy',canvas:{width:640,height:900},modules:[B.createModule('title',{id:'title',x:80,y:90,width:300,height:90,dataBinding:{path:'title'},style:{fontSize:32}})]});
const fabric=B.normalizeTemplate({...JSON.parse(JSON.stringify(legacy)),id:'fabric',fabricJson:{canvasWidth:640,canvasHeight:900,objects:[{type:'textbox',left:64,top:90,width:320,height:80,scaleX:1,scaleY:1,text:'Fabric title',fontSize:40}]}});const empty=B.normalizeTemplate({...JSON.parse(JSON.stringify(legacy)),id:'empty',fabricJson:{canvasWidth:640,canvasHeight:900,objects:[]}});state.visualTemplates.push(legacy,fabric,empty);
assert.equal(B.hasFabricScene(fabric),true);assert.equal(B.hasFabricScene(empty),false);assert.equal(B.hasFabricScene(legacy),false);assert.equal(B.normalizeTemplate(fabric).fabricJson.objects.length,1,'normalization preserves scene');
const legacyCard=B.renderBookCard(state.books[0]),fabricCard=B.renderBookCard(state.books[1]),emptyCard=B.renderBookCard(state.books[2]);assert.match(legacyCard,/data-visual-module="title"/);assert.match(fabricCard,/fabric-card-scene/);assert.match(fabricCard,/left:10%/);assert.match(emptyCard,/data-visual-module="title"/,'empty scene falls back to legacy modules');for(const html of [legacyCard,fabricCard,emptyCard])assert.match(html,/data-action="view-book" data-id=/,'whole card opens profile');
assert.doesNotMatch(canvas,/draft\.modules\s*=\s*modulesFromCanvas/);assert.match(canvas,/if\(scene\.objects\.length\)draft\.fabricJson=scene/);assert.match(css,/\.fabric-card-scene\{pointer-events:none\}/);console.log('legacy preservation, guarded Fabric scenes, uniform geometry, empty fallback, and card interaction assertions passed');
