'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('visual-builder.js','utf8'),css=fs.readFileSync('visual-builder.css','utf8'),app=fs.readFileSync('app.js','utf8');
const state={books:[{id:'book',title:'Fourth Wing',author:'Rebecca Yarros',series:'The Empyrean',summary:'A dragon-rider story.',status:'reading',progress:60,rating:4.5,spice:3,impact:5,trackerValues:{}}],sessions:[],visualTemplates:[]};
const context={globalThis:null,state,console,Date,Math,Number,String,Boolean,Array,Set,Map,saveState:()=>{},renderAll:()=>{},bookCardStats:()=>({notesCount:0,theoryCount:0,dossierCount:0,wallCount:0})};context.globalThis=context;vm.runInNewContext(source,context,{filename:'visual-builder.js'});const B=context.VisualBuilder;
const standard=B.standardBookTemplate(),regions=B.orderedRegions(standard);assert.equal(regions.map(region=>region.name).join('|'),'Header Region|Progress Region|Rating Region|Content Region|Action Region');assert.ok(regions.every(region=>region.layout==='responsive'&&region.visible));
const originalOrder=regions.map(region=>region.id);assert.equal(B.moveRegion(standard,'rating-group','up'),true);assert.notDeepEqual(B.orderedRegions(standard).map(region=>region.id),originalOrder);B.updateRegion(standard,'content-group',{visible:false,collapsed:true});assert.equal(standard.groups.find(region=>region.id==='content-group').visible,false);const hidden=B.renderTemplateCanvas(standard,state.books[0],{size:'large'});assert.doesNotMatch(hidden,/data-container-id="content-group"/);B.updateRegion(standard,'content-group',{visible:true,collapsed:false});const small=B.renderTemplateCanvas(standard,state.books[0],{size:'small'}),large=B.renderTemplateCanvas(standard,state.books[0],{size:'large'});assert.doesNotMatch(small,/data-visual-module="standard-summary"/,'compact density hides expanded content');assert.match(large,/data-visual-module="standard-summary"/,'expanded density reveals content');
const region=B.createRegion(standard,{name:'Quotes Region',role:'content'}),quote=B.createModule('quote',{id:'quote'});standard.modules.push(quote);B.assignModuleToRegion(standard,quote.id,region.id);assert.equal(quote.groupId,region.id);assert.equal(quote.responsive.mode,'responsive');B.convertModuleMode(standard,quote.id,'absolute');assert.equal(quote.responsive.mode,'absolute');const x=quote.x;B.convertModuleMode(standard,quote.id,'responsive',region.id);assert.equal(quote.x,x,'mode conversion preserves expert coordinates');
for(const style of ['minimal','classic','dramatic','cozy','dark-academia','custom']){standard.composer.stylePreset=style;assert.match(B.renderTemplateCanvas(standard,state.books[0]),new RegExp(`data-card-style="${style}"`));}for(const typography of ['elegant','modern','bold','compact']){standard.composer.typography=typography;assert.match(B.renderTemplateCanvas(standard,state.books[0]),new RegExp(`data-card-typography="${typography}"`));}
const legacy=B.normalizeTemplate({id:'legacy-expert',schemaVersion:3,canvas:{width:420,height:380},groups:[{id:'free',layout:'freeform'}],modules:[{id:'positioned',type:'text',groupId:'free',x:117,y:83,width:199,height:77}]});assert.equal(legacy.composer.enabled,false);assert.equal(legacy.modules[0].x,117);assert.equal(legacy.modules[0].width,199);const modern=B.createTemplate({name:'New Composer Card'});assert.equal(modern.composer.enabled,true);
standard.id='composer-test';state.books[0].visualTemplateId=standard.id;const preview=B.renderTemplateCanvas(standard,state.books[0],{size:'medium',presentation:'card'});state.visualTemplates.push(standard);const production=B.renderBookCard(state.books[0],{size:'medium'});assert.equal(production.slice(production.indexOf('<div class=\"visual-book-canvas'),production.lastIndexOf('</article>')),preview,'composer preview and production use identical renderer output');
for(const hook of ['Card Composer','data-composer-style','data-composer-density','data-composer-typography','data-toggle-region','data-region-visible','data-region-up','data-region-down','data-module-region'])assert.ok(source.includes(hook),hook);assert.match(source,/editingMode=editorDraft\.composer\.enabled\?'composer':'expert'/);assert.match(app,/size:compact\?'small':state\.libraryPreferences\?\.cardSize/);
for(const selector of ['data-card-style=minimal','data-card-style=classic','data-card-style=dramatic','data-card-style=cozy','data-card-style=dark-academia','data-container-role=header','data-container-role=content','data-presentation=list'])assert.ok(css.includes(selector),selector);assert.match(css,/\.builder-inspector:not\(\.has-selection\)\{display:none\}/);assert.match(css,/@media\(max-width:650px\)/);assert.doesNotMatch(css.slice(css.indexOf('/* Friendly Card Composer')),/(#[0-9a-f]{3,8}|rgba?\()/i);
console.log('composer regions, density visibility, friendly styles, expert migration, and shared rendering assertions passed');
