'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('visual-builder.js','utf8'),css=fs.readFileSync('visual-builder.css','utf8');
const book={id:'book',title:'Fourth Wing',author:'Rebecca Yarros',series:'The Empyrean',status:'reading',progress:50,rating:4.5,spice:3,impact:5,trackerValues:{}},state={books:[book],sessions:[],visualTemplates:[]};
const context={globalThis:null,state,console,Date,Math,Number,String,Boolean,Array,Set,Map,saveState(){},renderAll(){},bookCardStats(){return{notesCount:0,theoryCount:0,dossierCount:0,wallCount:0}}};context.globalThis=context;vm.runInNewContext(source,context);const B=context.VisualBuilder;
const title=B.createModule('title',{id:'title'}),rating=B.createModule('rating',{id:'rating'});assert.deepEqual([title.width,title.height],[220,52]);assert.deepEqual([rating.width,rating.height],[120,52]);
const template=B.createTemplate({id:'free',canvas:{width:640,height:900,size:'custom'},modules:[title,rating]});assert.equal(template.composer.enabled,false);B.moveModule(template,'title',96,144);B.resizeModule(template,'title',304,88);const saved=B.normalizeTemplate(JSON.parse(JSON.stringify(template)));assert.deepEqual([saved.modules[0].x,saved.modules[0].y,saved.modules[0].width,saved.modules[0].height],[96,144,304,88]);
for(const size of ['small','medium','large']){const html=B.renderTemplateCanvas(saved,book,{size});assert.match(html,/data-layout-mode="absolute"/);assert.match(html,/--module-x:15%/);assert.match(html,/--module-width:47\.5%/);}
const migrated=B.normalizeTemplate({id:'composer',composer:{enabled:true},canvas:{width:640,height:900},groups:[{id:'header',layout:'responsive'}],modules:[{id:'legacy',type:'title',groupId:'header',x:77,y:91,width:244,height:66,responsive:{mode:'responsive'},dataBinding:{path:'title'}}]});assert.equal(migrated.composer.enabled,false);assert.equal(migrated.modules[0].responsive.mode,'absolute');assert.equal(migrated.modules[0].groupId,'');assert.deepEqual([migrated.modules[0].x,migrated.modules[0].y,migrated.modules[0].width,migrated.modules[0].height],[77,91,244,66]);
const preview=B.renderTemplateCanvas(saved,book,{size:'medium'});book.visualTemplateId=saved.id;state.visualTemplates.push(saved);assert.ok(B.renderBookCard(book,{size:'medium'}).includes(preview));
for(const hook of ['Freeform Design','data-layout-mode="absolute"','data-inspect-x','data-inspect-width','data-layer','data-canvas-snap'])assert.ok(source.includes(hook),hook);for(const rule of ['Freeform design space','data-layout-mode=absolute','is-builder-module:not(.is-selected)','font-size:max(14px','data-card-size=large'])assert.ok(css.includes(rule),rule);assert.doesNotMatch(css.slice(css.lastIndexOf('Freeform design space')),/(#[0-9a-f]{3,8}|rgba?\()/i);
console.log('freeform movement, resizing, persistence, hug bounds, proportional display scaling, migration, shared preview, and theme assertions passed');
