const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const app = fs.readFileSync('app.js','utf8');
const css = fs.readFileSync('dossier-experience.css','utf8');
const wall = fs.readFileSync('infinite-wall.js','utf8');
const wallCss = fs.readFileSync('infinite-wall.css','utf8');

assert.match(app,/libraryFiltersOpen=false/);
assert.match(app,/<details class="library-preferences"/);
assert.match(app,/Library View & Filters/);
assert.match(app,/library-mobile-header/);
assert.ok(app.indexOf('library-mobile-header') < app.indexOf('<details class="library-preferences"'));
assert.match(app,/data-library-layout="\$\{prefs\.layout\}"/);
assert.match(app,/data-card-size="\$\{prefs\.cardSize\}"/);
assert.match(css,/data-library-layout="list"/);
assert.match(css,/data-library-layout="cards"/);
for(const size of ['small','medium','large']) assert.match(css,new RegExp(`data-card-size="${size}"`));
for(const key of ['cover','author','series','status','progress','rating','spice','impact','reaction','actions']) assert.match(app,new RegExp(`${key}:'[^']+'`));
assert.match(app,/data-library-visible/);
assert.match(app,/prefs\.visible\[input\.dataset\.libraryVisible\]=input\.checked/);
assert.match(app,/libraryPreferences:\{sort:'added',group:'none',layout:'list',cardSize:'medium'/);
assert.match(app,/visible:\{\.\.\.defaults\.visible,\.\.\.\(saved\.visible\|\|\{\}\)\}/);
assert.match(app,/list="bookAuthorSuggestions"/);
assert.match(app,/list="bookSeriesSuggestions"/);
assert.match(app,/uniqueBookValues\('author'\)/);
assert.match(app,/uniqueBookValues\('series'\)/);
assert.match(app,/step="0\.5"/);
assert.doesNotMatch(app,/Math\.round\([^\n]*(rating|spice|impact)/i);
const helperStart=app.indexOf('function uniqueBookValues');
const helperEnd=app.indexOf('function libraryVisibilityControls',helperStart);
const context={state:{books:[{author:' Rebecca  Yarros ',series:' Empyrean '},{author:'rebecca yarros',series:'empyrean'},{author:'Brandon Sanderson',series:'Mistborn'}]}};
vm.runInNewContext(`${app.slice(helperStart,helperEnd)};this.uniqueBookValues=uniqueBookValues;this.formatRatingValue=formatRatingValue`,context);
assert.deepStrictEqual([...context.uniqueBookValues('author')],['Brandon Sanderson','Rebecca Yarros']);
assert.deepStrictEqual([...context.uniqueBookValues('series')],['Empyrean','Mistborn']);
assert.strictEqual(context.formatRatingValue(4.5),'4.5');
assert.strictEqual(context.formatRatingValue(4),'4');
assert.strictEqual(context.formatRatingValue(2.5),'2.5');
assert.match(wall,/id="mobileWallSelect"/);
assert.match(wall,/mobileWallSelect\.onchange/);
assert.match(wall,/state\.activeWallId=event\.target\.value/);
assert.match(wall,/data-action="new-wall"/);
assert.match(wall,/data-action="edit-wall"/);
assert.match(wallCss,/@media\(max-width:800px\)\{\.wall-tabs\{display:none!important\}/);
assert.match(wallCss,/\.mobile-wall-selector option\{white-space:normal/);

const runtime={__ABILITY_TEST__:true,console,setTimeout,clearTimeout,localStorage:{getItem:()=>null,setItem:()=>{}},globalThis:null};runtime.globalThis=runtime;vm.runInNewContext(app,runtime,{filename:'app.js'});const saved={books:[{id:'half',title:'Half values',rating:4.5,spice:2.5,impact:3.5}],libraryPreferences:{layout:'comfortable',cardSize:'large',visible:{cover:false}}};const normalized=runtime.AbilityCatalog.normalizeState(saved);assert.strictEqual(normalized.books[0].rating,4.5);assert.strictEqual(normalized.books[0].spice,2.5);assert.strictEqual(normalized.books[0].impact,3.5);assert.strictEqual(normalized.libraryPreferences.layout,'cards');assert.strictEqual(normalized.libraryPreferences.cardSize,'large');assert.strictEqual(normalized.libraryPreferences.visible.cover,false);assert.strictEqual(normalized.libraryPreferences.visible.author,true);assert.deepStrictEqual(JSON.parse(JSON.stringify(runtime.AbilityCatalog.normalizeState(normalized).libraryPreferences)),JSON.parse(JSON.stringify(normalized.libraryPreferences)));
console.log('final mobile library, ratings, autocomplete, and wall selector assertions passed');
