'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const assetsSource=fs.readFileSync('visual-assets.js','utf8'),fontsSource=fs.readFileSync('visual-fonts.js','utf8'),canvasSource=fs.readFileSync('canvas-editor.js','utf8'),builder=fs.readFileSync('visual-builder.js','utf8'),bridge=fs.readFileSync('supabase-bridge.js','utf8'),migration=fs.readFileSync('migrations/202608030001_private_visual_libraries.sql','utf8'),index=fs.readFileSync('index.html','utf8');
function load(source,extra={}){const context={globalThis:null,console,Set,Map,Promise,Uint8Array,String,Number,Date,...extra};context.globalThis=context;vm.runInNewContext(source,context);return context;}
const PNG=new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0]),JPG=new Uint8Array([255,216,255,224]),WEBP=new Uint8Array([82,73,70,70,0,0,0,0,87,69,66,80]),WOFF2=new Uint8Array([119,79,70,50]),WOFF=new Uint8Array([119,79,70,70]),TTF=new Uint8Array([0,1,0,0]),OTF=new Uint8Array([79,84,84,79]);
const file=(name,type,data,size=data.length)=>({name,type,size,slice:(start,end)=>({arrayBuffer:async()=>data.slice(start,end).buffer})});
(async()=>{
 const A=load(assetsSource).VisualAssets;for(const [name,type,data] of [['dragon.png','image/png',PNG],['photo.jpg','image/jpeg',JPG],['texture.webp','image/webp',WEBP]])assert.equal((await A.validate(file(name,type,data))).mimeType,type);await assert.rejects(A.validate(file('unsafe.svg','image/svg+xml',PNG)),/PNG, JPG, or WebP/);await assert.rejects(A.validate(file('large.png','image/png',PNG,8*1024*1024+1)),/8 MB/);await assert.rejects(A.validate(file('fake.png','image/png',JPG)),/signature/);
 const F=load(fontsSource).VisualFonts;for(const [name,type,data] of [['horror.woff2','font/woff2',WOFF2],['script.woff','font/woff',WOFF],['fantasy.ttf','font/ttf',TTF],['gothic.otf','font/otf',OTF]])assert.ok((await F.validate(file(name,type,data))).fontFormat);await assert.rejects(F.uploadFont(file('font.woff2','font/woff2',WOFF2),{licenseConfirmed:false}),/Confirm/);await assert.rejects(F.validate(file('bad.exe','application/octet-stream',WOFF2)),/WOFF2/);await assert.rejects(F.validate(file('large.woff2','font/woff2',WOFF2,5*1024*1024+1)),/5 MB/);
 assert.match(migration,/create table if not exists public\.visual_assets/);assert.match(migration,/create table if not exists public\.custom_fonts/);assert.match(migration,/false,8388608/);assert.match(migration,/auth\.uid\(\)=user_id/g);assert.match(migration,/storage\.foldername\(name\)\)\[1\]=auth\.uid\(\)::text/g);assert.doesNotMatch(migration,/service_role/);
 assert.match(bridge,/createSignedUrl\(path, 3600\)/);assert.match(bridge,/path = `\$\{account\.id\}\/\$\{id\}/);assert.match(bridge,/await supabase\.storage\.from\(bucket\)\.remove/);assert.match(bridge,/window\.VisualCloud/);assert.doesNotMatch(bridge,/getPublicUrl/);
 for(const api of ['listAssets','uploadAsset','deleteAsset','renameAsset','getAssetUrl','refreshAssetLibrary'])assert.ok(assetsSource.includes(api));for(const api of ['listFonts','uploadFont','loadFont','loadAllUserFonts','deleteFont','renameFont','refreshFontLibrary'])assert.ok(fontsSource.includes(api));
 const canvasContext=load(canvasSource,{document:{addEventListener(){}},window:{},Image:function(){}}),saved=canvasContext.CanvasEditor.serializeCanvas({toJSON:()=>({objects:[{type:'Image',src:'https://temporary.test/signed',assetId:'asset-1',assetStoragePath:'owner/asset-1/dragon.png'},{type:'Textbox',fontId:'font-1',fontFamilyKey:'UserFont_1',fontStoragePath:'owner/font-1/font.woff2'}]})});assert.equal(saved.objects[0].src,undefined);assert.equal(saved.objects[0].assetId,'asset-1');assert.equal(saved.objects[0].assetStoragePath,'owner/asset-1/dragon.png');assert.equal(saved.objects[1].fontId,'font-1');assert.equal(saved.objects[1].fontStoragePath,'owner/font-1/font.woff2');
 assert.match(canvasSource,/globalThis\.CanvasEditor/);assert.match(canvasSource,/assetStoragePath/);assert.match(canvasSource,/fontId/);assert.match(canvasSource,/delete object\.src/);assert.match(canvasSource,/object\.initDimensions\?\.\(\)/);assert.match(canvasSource,/object\.setCoords\?\.\(\)/);assert.match(canvasSource,/editor\.canvas\.requestRenderAll\(\)/);assert.match(canvasSource,/visual element is unavailable/);assert.match(builder,/CanvasEditor\?\.openBookCardEditor/);assert.match(canvasSource,/data-fabric-field/);assert.match(canvasSource,/data-fabric-asset-upload/);assert.match(canvasSource,/data-fabric-font-upload/);assert.match(index,/fabric@6/);for(const global of ['visual-fields.js','visual-assets.js','visual-fonts.js','canvas-editor.js','visual-builder.js'])assert.ok(bridge.indexOf(global)>=0,global);assert.ok(bridge.indexOf('visual-fields.js')<bridge.indexOf('visual-assets.js')&&bridge.indexOf('visual-fonts.js')<bridge.indexOf('canvas-editor.js')&&bridge.indexOf('canvas-editor.js')<bridge.indexOf('visual-builder.js'));
 console.log('private visual asset/font validation, RLS, signed URLs, stable Fabric references, and runtime handoff assertions passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
