'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('visual-builder.js','utf8');
const css=fs.readFileSync('visual-builder.css','utf8');
const context={globalThis:null,console,Date,Math,Number,String,Boolean,Array,Set,Map};context.globalThis=context;
vm.runInNewContext(source,context,{filename:'visual-builder.js'});
const B=context.VisualBuilder;
assert.equal(B.BUILDER_SCHEMA_VERSION,2);
for(const type of ['text','image','title','metadata','rating','slider','progress','stars','icons','counter','linked-record','linked-dossier','linked-theory','relationship-count','quote','notes','tags','custom'])assert.ok(B.MODULE_TYPES.includes(type),type);
const template=B.createTemplate({id:'template-1',name:'Generic Archive Layout',type:'generic',canvas:{width:700,height:500,grid:10}});
assert.equal(template.id,'template-1');assert.equal(template.theme.mode,'inherit');assert.equal(template.modules.length,0);
const item=B.createModule('custom',{id:'module-1',name:'Emotional Damage',x:10,y:20,width:180,height:90,config:{icon:'💔',max:5},dataBinding:{path:'ratings.impact'}});
template.modules.push(item);
B.moveModule(template,item.id,42,64);assert.equal(item.x,40);assert.equal(item.y,60);
B.resizeModule(template,item.id,260,140);assert.equal(item.width,260);assert.equal(item.height,140);
B.lockModule(template,item.id,true);assert.equal(item.locked,true);assert.equal(B.moveModule(template,item.id,0,0),null);
B.lockModule(template,item.id,false);B.updateModuleStyle(template,item.id,{display:'hearts'});assert.equal(item.style.display,'hearts');
const copy=B.duplicateModule(template,item.id);assert.notEqual(copy.id,item.id);assert.equal(copy.name,'Emotional Damage copy');assert.equal(template.modules.length,2);
assert.equal(B.deleteModule(template,copy.id),true);assert.equal(template.modules.length,1);
const stored=JSON.stringify(template),loaded=B.normalizeTemplate(JSON.parse(stored));assert.equal(JSON.stringify(loaded),stored,'template save/load is stable');
const twice=JSON.stringify(B.normalizeTemplate(loaded));assert.equal(twice,stored,'template migration is idempotent');
assert.match(source,/data-builder-canvas/);assert.match(source,/data-builder-resize/);assert.match(source,/data-nudge-x/);assert.match(source,/data-size-x/);assert.match(source,/data-builder-undo/);assert.match(source,/recordType:String\(template\.target/);
for(const variable of ['--ui-surface','--ui-surface-raised','--ui-border','--ui-text','--ui-accent','--ui-focus'])assert.ok(css.includes(`var(${variable}`),variable);
assert.doesNotMatch(css,/(#[0-9a-f]{3,8}|rgb\()/i,'builder CSS contains no hard-coded colors');
assert.match(css,/@media\(max-width:650px\)/);assert.match(css,/min-height:44px/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);
console.log('universal visual builder assertions passed');
