'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const fieldsSource=fs.readFileSync('visual-fields.js','utf8'),builderSource=fs.readFileSync('visual-builder.js','utf8'),canvasSource=fs.readFileSync('canvas-editor.js','utf8'),bridge=fs.readFileSync('supabase-bridge.js','utf8');
const context={globalThis:null,state:{books:[],sessions:[],visualTemplates:[],bookConnections:[{fromBookId:'book',toBookId:'other'}]},console,Date,Math,Number,String,Boolean,Array,Set,Map,JSON,saveState(){},renderAll(){},bookCardStats(){return{notesCount:0,theoryCount:0,dossierCount:0,wallCount:0}}};
context.globalThis=context;
vm.runInNewContext(fieldsSource,context,{filename:'visual-fields.js'});
vm.runInNewContext(canvasSource,context,{filename:'canvas-editor.js'});
vm.runInNewContext(builderSource,context,{filename:'visual-builder.js'});
const book={id:'book',title:'Onyx Storm',author:'Rebecca Yarros',series:'The Empyrean',coverUrl:'cover.jpg',genres:['Romantasy','Dragons'],tags:['favorite'],rating:0,spice:0,impact:0,ratings:{overall:4.5,spice:2,impact:3,reaction:'Loved it'},notes:[{text:'Keep this'}],linkedDossierIds:['d1'],progress:72};
assert.equal(typeof context.VisualFields,'object');
assert.ok(context.VisualFields.fields().length>=20);
assert.equal(context.VisualFields.resolve(book,'coverUrl'),'cover.jpg');
assert.equal(context.VisualFields.resolve(book,'rating'),4.5);
assert.equal(context.VisualFields.display(book,'genres'),'Romantasy, Dragons');
assert.equal(context.VisualFields.display(book,'linkedDossierIds'),'1');
assert.equal(context.VisualFields.display(book,'bookConnections'),'1');
const coverModule=context.VisualBuilder.createBoundModule('coverUrl');
assert.equal(coverModule.type,'image');
assert.equal(coverModule.dataBinding.path,'coverUrl');
const genresModule=context.VisualBuilder.createBoundModule('genres');
assert.equal(genresModule.type,'tags');
const rebound=context.CanvasEditor.bindRecord({version:'6',objects:[{type:'Image',id:'cover',cardRole:'image',dataBinding:{path:'coverUrl'},src:'old.jpg'}]},book);
assert.equal(rebound.objects[0].src,'cover.jpg');
assert.match(bridge,/visual-fields\.js', 'canvas-editor\.js', 'visual-builder\.js/);
console.log('visual field registry, bound modules, and image rebinding assertions passed');
