'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('infinite-wall.js','utf8');
const css=fs.readFileSync('infinite-wall.css','utf8');
const start=source.indexOf('  const MIN_ZOOM');
const end=source.indexOf('  const dossierById',start);
assert.ok(start>0&&end>start,'interaction math block is discoverable');
const context={result:null,Map,Number,Math};
vm.runInNewContext(`${source.slice(start,end)}\nresult={clampWallScale,screenDeltaToWorldDelta,calculatePinchScale,calculateAnchoredViewport,calculateFitBounds,calculateFitViewport,sanitizeViewport};`,context);
const M=context.result;
assert.equal(M.clampWallScale(-5),.2);assert.equal(M.clampWallScale(99),2.5);assert.equal(M.clampWallScale(NaN),1);
assert.equal(M.calculatePinchScale(1,100,200),2);assert.equal(M.calculatePinchScale(2,100,1000),2.5);
const anchored=M.calculateAnchoredViewport({panX:0,panY:0,zoom:1},{x:100,y:80},{x:220,y:190},2);assert.deepEqual(JSON.parse(JSON.stringify(anchored)),{panX:20,panY:30,zoom:2});
assert.equal(M.screenDeltaToWorldDelta(40,2),20);
const bounds=M.calculateFitBounds([{x:-100,y:20,width:200,height:80},{x:300,y:-50,width:100,height:150},{x:NaN,y:0,width:10,height:10}]);assert.deepEqual(JSON.parse(JSON.stringify(bounds)),{minX:-100,minY:-50,maxX:400,maxY:100});
const fitted=M.calculateFitViewport(bounds,1000,600,50);assert.ok(fitted.zoom>=.2&&fitted.zoom<=2.5);assert.ok(Number.isFinite(fitted.panX)&&Number.isFinite(fitted.panY));
assert.deepEqual(JSON.parse(JSON.stringify(M.calculateFitViewport(null,320,480))),{panX:160,panY:240,zoom:1});
assert.deepEqual(JSON.parse(JSON.stringify(M.sanitizeViewport({panX:Infinity,panY:'bad',zoom:90}))),{panX:0,panY:0,zoom:2.5});
assert.match(source,/bindCanvasGestures\(canvas\)/);assert.doesNotMatch(source,/bindCanvasPan\(/);assert.match(source,/wallGesture\.pointers\.size===2/);assert.match(source,/onpointercancel/);assert.match(source,/onlostpointercapture/);
assert.match(source,/data-fit-all>Fit Wall/);assert.match(source,/data-reset-view>Reset View/);assert.match(source,/data-card-menu/);assert.match(source,/openConnectionsManager/);assert.match(source,/queueSave\(\).*Pinching|pinching[\s\S]*queueSave\(\)/);
assert.match(css,/env\(safe-area-inset-bottom\)/);assert.match(css,/\.mobile-wall-controls/);assert.match(css,/min-height:44px/);assert.match(css,/@media\(hover:none\),\(pointer:coarse\)/);assert.match(css,/\.infinite-canvas\{touch-action:none/);
assert.equal((source.match(/function bindCanvasGestures/g)||[]).length,1,'one canvas gesture owner');
console.log('wall interaction assertions passed');
