'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const source=fs.readFileSync('infinite-wall.js','utf8');
const css=fs.readFileSync('infinite-wall.css','utf8');
const dossierCss=fs.readFileSync('dossier-experience.css','utf8');
assert.match(source,/desktop-wall-actions[\s\S]*data-review-duplicates/,'desktop duplicate review action is rendered');
const sheet=source.slice(source.indexOf('<aside id="mobileWallTools"'),source.indexOf('</aside>',source.indexOf('<aside id="mobileWallTools"')));
assert.match(sheet,/Review Duplicate Appearances/);assert.match(sheet,/data-review-duplicates/);
assert.match(source,/function duplicateAppearanceReport/);assert.match(source,/creationSource/);assert.match(source,/Duplicate Appearance Report/);
const start=source.indexOf('  function canonicalDossierForLegacyCard'),end=source.indexOf('  function appearanceOnWall',start),context={state:{dossiers:[{id:'canonical-bodhi',title:'Bodhi Durran',sourceType:'character',sourceId:'bodhi'}]},result:null};require('node:vm').runInNewContext(`${source.slice(start,end)};result=canonicalDossierForLegacyCard({id:'legacy-placement',sourceType:'character',sourceId:'bodhi'});`,context);assert.equal(context.result.id,'canonical-bodhi','refresh migration reuses Bodhi canonical dossier instead of creating another');
assert.match(source,/function canonicalDossierForLegacyCard/);assert.match(source,/item\.sourceType===card\.sourceType&&item\.sourceId===card\.sourceId/,'legacy source identity reuses canonical dossier');
assert.match(source,/if\(existing&&!options\.allowDuplicate\)return\{appearance:existing,created:false\}/,'same wall duplicate stays blocked');
assert.match(source,/id="mobileWallSelect"/);assert.match(source,/state\.activeWallId=event\.target\.value/);assert.match(source,/rememberUiLocation\(\)/);assert.match(source,/saveState\(\);renderWall/);
assert.match(source,/class="wall-tabs"/);assert.match(source,/data-action="new-wall"/);assert.match(source,/data-action="edit-wall"/);
assert.doesNotMatch(dossierCss,/\.mobile-wall-selector\{display:none\}/,'later-loaded dossier CSS no longer hides shared selector');
assert.match(css,/@media\(max-width:800px\)\{\.wall-tabs\{display:none!important\}\.mobile-wall-selector\{display:grid!important\}/);
assert.match(css,/\.desktop-wall-actions button[^{]*\{appearance:none/);assert.match(css,/background:var\(--ui-surface-raised/);
console.log('wall navigation and duplicate diagnostics assertions passed');
