import { useEffect, useMemo, useRef, useState } from 'react';
import type { V2ArchiveState, V2BookRecord } from './archive';
import type { SuspicionRecord, TheoryRecord, WallCardDisplay, WallCardRecord, WallDossierCategory, WallDossierRecord, WallRecord, WallRegionRecord, WallRegionRule, WallSourceType } from './domain';
import './conspiracy-wall.css';

type Source = {
  type: WallSourceType;
  id: string;
  category: string;
  title: string;
  shortSummary: string;
  overview: string;
  notes?: string;
  status?: string;
  confidence?: number;
  bookIds: string[];
  theoryIds: string[];
  suspicionIds: string[];
  dossierIds: string[];
};

type Interaction =
  | { kind: 'card'; id: string; startX: number; startY: number; x: number; y: number }
  | { kind: 'region'; id: string; startX: number; startY: number; x: number; y: number; children: Array<{ id: string; x: number; y: number }> }
  | { kind: 'card-resize'; id: string; startX: number; startY: number; width: number; height: number }
  | { kind: 'region-resize'; id: string; startX: number; startY: number; width: number; height: number };

type ProfileDraft = {
  title: string;
  shortSummary: string;
  overview: string;
  notes: string;
  status: string;
  confidence: number;
  bookIds: string[];
  theoryIds: string[];
  suspicionIds: string[];
  dossierIds: string[];
};

const WALL_KEY = 'empyrean-v2-active-wall';
const ZOOM_KEY = 'empyrean-v2-wall-zoom';
const MIN_ZOOM = .35;
const MAX_ZOOM = 2;
const REGION_HEADER = 58;
const CATEGORIES: WallDossierCategory[] = ['character', 'location', 'faction', 'object', 'event', 'creature', 'custom'];
const RULES: Array<{ value: WallRegionRule; label: string }> = [
  { value: 'manual', label: 'Manual placement' }, { value: 'any', label: 'Any unassigned card' },
  { value: 'book', label: 'Books' }, { value: 'theory', label: 'Theories' }, { value: 'suspicion', label: 'Suspicions' },
  { value: 'dossier', label: 'Wall dossiers' }, { value: 'open-investigation', label: 'Open investigations' }, { value: 'resolved-investigation', label: 'Resolved investigations' },
];
const DEFAULT_DISPLAY: WallCardDisplay = { density: 'standard', showCategory: true, showSummary: true, showCounts: true, showStatus: true, categoryStyle: 'text', countsStyle: 'text' };
const EMPTY_PROFILE: ProfileDraft = { title: '', shortSummary: '', overview: '', notes: '', status: '', confidence: 0, bookIds: [], theoryIds: [], suspicionIds: [], dossierIds: [] };

function now() { return new Date().toISOString(); }
function clamp(value: number, min: number, max: number) { return Math.max(min, Math.min(max, value)); }
function alpha(color: string, suffix: string) { return /^#[0-9a-f]{6}$/i.test(color) ? `${color}${suffix}` : `#a64f24${suffix}`; }
function readActive() { try { return localStorage.getItem(WALL_KEY) || ''; } catch { return ''; } }
function readZoom(id: string) { try { const map = JSON.parse(localStorage.getItem(ZOOM_KEY) || '{}') as Record<string, number>; return clamp(Number(map[id]) || 1, MIN_ZOOM, MAX_ZOOM); } catch { return 1; } }
function writeZoom(id: string, zoom: number) { try { const map = JSON.parse(localStorage.getItem(ZOOM_KEY) || '{}') as Record<string, number>; map[id] = zoom; localStorage.setItem(ZOOM_KEY, JSON.stringify(map)); } catch { /* unavailable */ } }
function newWall(title: string): WallRecord { const stamp = now(); return { id: crypto.randomUUID(), title, cards: [], regions: [], canvasWidth: 1900, canvasHeight: 1200, createdAt: stamp, updatedAt: stamp }; }
function plural(count: number, label: string) { return `${count} ${label}${count === 1 ? '' : 's'}`; }
function selectedValues(event: React.ChangeEvent<HTMLSelectElement>) { return Array.from(event.currentTarget.selectedOptions).map((option) => option.value); }
function displayFor(card: WallCardRecord): WallCardDisplay { return { ...DEFAULT_DISPLAY, ...(card.kind === 'reference' ? { showSummary: false, showStatus: false } : {}), ...(card.display || {}) }; }
function minimumCardHeight(display: WallCardDisplay, kind: WallCardRecord['kind']) { let value = kind === 'reference' ? 118 : 142; if (display.showCategory) value += 20; if (display.showSummary) value += 78; if (display.showCounts) value += 54; if (display.showStatus) value += 34; return value; }

export function ConspiracyWall({ archive, onSave }: { archive: V2ArchiveState; onSave: (next: V2ArchiveState) => Promise<void> }) {
  const fallback = useRef(newWall('Primary Conspiracy Wall'));
  const viewport = useRef<HTMLDivElement>(null);
  const interaction = useRef<Interaction | null>(null);
  const moved = useRef(false);
  const [activeId, setActiveId] = useState(readActive);
  const wall = archive.walls.find((item) => item.id === activeId) ?? archive.walls[0] ?? fallback.current;
  const [zoom, setZoom] = useState(() => readZoom(activeId || 'default'));
  const [search, setSearch] = useState('');
  const [filterType, setFilterType] = useState<'all' | WallSourceType>('all');
  const [filterRegion, setFilterRegion] = useState('all');
  const [showFilters, setShowFilters] = useState(false);
  const [showBoardMenu, setShowBoardMenu] = useState(false);
  const [previewId, setPreviewId] = useState<string | null>(null);
  const [regionSettingsId, setRegionSettingsId] = useState<string | null>(null);
  const [showDossierForm, setShowDossierForm] = useState(false);
  const [appearanceRegion, setAppearanceRegion] = useState('');
  const [targetWallId, setTargetWallId] = useState('');
  const [editingProfile, setEditingProfile] = useState(false);
  const [overviewOpen, setOverviewOpen] = useState(true);
  const [displayOpen, setDisplayOpen] = useState(false);
  const [connectionsOpen, setConnectionsOpen] = useState(true);
  const [placementsOpen, setPlacementsOpen] = useState(false);
  const [profileDraft, setProfileDraft] = useState<ProfileDraft>(EMPTY_PROFILE);
  const [draft, setDraft] = useState({ category: 'character' as WallDossierCategory, title: '', shortSummary: '', overview: '', notes: '', bookIds: [] as string[], theoryIds: [] as string[], suspicionIds: [] as string[], dossierIds: [] as string[] });

  useEffect(() => { setZoom(readZoom(wall.id)); }, [wall.id]);

  const sources = useMemo<Source[]>(() => [
    ...archive.books.map((book) => ({ type: 'book' as const, id: book.id, category: 'book', title: book.title, shortSummary: book.summary || book.author || 'No one-sentence summary yet.', overview: book.about || book.summary || book.reaction || '', notes: (book.notes || []).map((note) => note.text).join('\n'), status: book.status, bookIds: [book.id], theoryIds: book.theoryIds || [], suspicionIds: book.suspicionIds || [], dossierIds: [] })),
    ...archive.theories.map((item) => ({ type: 'theory' as const, id: item.id, category: 'theory', title: item.title, shortSummary: item.statement.split(/(?<=[.!?])\s/)[0] || item.statement, overview: item.statement, notes: item.evidence.map((entry) => entry.text).join('\n'), status: item.status, confidence: item.confidence, bookIds: item.bookIds, theoryIds: [], suspicionIds: [], dossierIds: [] })),
    ...archive.suspicions.map((item) => ({ type: 'suspicion' as const, id: item.id, category: 'suspicion', title: item.title, shortSummary: item.details.split(/(?<=[.!?])\s/)[0] || item.details, overview: item.details, notes: item.evidence.map((entry) => entry.text).join('\n'), status: item.status, confidence: item.confidence, bookIds: item.bookIds, theoryIds: [], suspicionIds: [], dossierIds: [] })),
    ...archive.dossiers.map((item) => ({ type: 'dossier' as const, id: item.id, category: item.category, title: item.title, shortSummary: item.shortSummary || 'No one-sentence summary yet.', overview: item.overview || '', notes: item.notes || '', status: 'active', bookIds: item.bookIds, theoryIds: item.theoryIds, suspicionIds: item.suspicionIds, dossierIds: item.dossierIds })),
  ], [archive.books, archive.dossiers, archive.suspicions, archive.theories]);

  const sourceMap = useMemo(() => new Map(sources.map((source) => [`${source.type}:${source.id}`, source])), [sources]);
  const sourceFor = (card: WallCardRecord | null) => card ? sourceMap.get(`${card.sourceType}:${card.sourceId}`) : undefined;
  const homeFor = (card: WallCardRecord) => card.kind === 'home' ? card : wall.cards.find((item) => item.id === card.homeCardId) ?? wall.cards.find((item) => item.kind === 'home' && item.sourceType === card.sourceType && item.sourceId === card.sourceId);
  const previewCard = wall.cards.find((card) => card.id === previewId) ?? null;
  const previewHome = previewCard ? homeFor(previewCard) : undefined;
  const previewSource = sourceFor(previewCard);
  const previewDisplay = previewCard ? displayFor(previewCard) : DEFAULT_DISPLAY;
  const regionSettings = wall.regions.find((region) => region.id === regionSettingsId) ?? null;

  useEffect(() => {
    if (!previewSource) return;
    setProfileDraft({ title: previewSource.title, shortSummary: previewSource.shortSummary === 'No one-sentence summary yet.' ? '' : previewSource.shortSummary, overview: previewSource.overview, notes: previewSource.notes || '', status: previewSource.status || '', confidence: previewSource.confidence || 0, bookIds: [...previewSource.bookIds], theoryIds: [...previewSource.theoryIds], suspicionIds: [...previewSource.suspicionIds], dossierIds: [...previewSource.dossierIds] });
    setEditingProfile(false);
  }, [previewSource?.id, previewSource?.type]);

  const available = useMemo(() => { const query = search.trim().toLowerCase(); return sources.filter((source) => !wall.cards.some((card) => card.kind === 'home' && card.sourceType === source.type && card.sourceId === source.id) && (!query || `${source.title} ${source.shortSummary} ${source.category}`.toLowerCase().includes(query))).slice(0, 25); }, [search, sources, wall.cards]);
  const visibleIds = useMemo(() => new Set(wall.cards.filter((card) => { const source = sourceFor(card); if (!source) return false; if (filterType !== 'all' && source.type !== filterType) return false; if (filterRegion !== 'all' && (filterRegion === 'unassigned' ? Boolean(card.regionId) : card.regionId !== filterRegion)) return false; return true; }).map((card) => card.id)), [filterRegion, filterType, sourceMap, wall.cards]);

  async function save(next: V2ArchiveState) { await onSave(next); }
  async function saveWall(nextWall: WallRecord) { const stamped = { ...nextWall, updatedAt: now() }; const walls = archive.walls.some((item) => item.id === stamped.id) ? archive.walls.map((item) => item.id === stamped.id ? stamped : item) : [...archive.walls, stamped]; await save({ ...archive, walls }); }
  function setActive(id: string) { setActiveId(id); try { localStorage.setItem(WALL_KEY, id); } catch { /* unavailable */ } }
  function changeZoom(value: number) { const next = clamp(Math.round(value * 100) / 100, MIN_ZOOM, MAX_ZOOM); setZoom(next); writeZoom(wall.id, next); }
  async function updateCard(id: string, changes: Partial<WallCardRecord>) { await saveWall({ ...wall, cards: wall.cards.map((card) => card.id === id ? { ...card, ...changes, updatedAt: now() } : card) }); }
  async function updateDisplay(changes: Partial<WallCardDisplay>) { if (!previewCard) return; const display = { ...displayFor(previewCard), ...changes }; await updateCard(previewCard.id, { display, height: Math.max(previewCard.height, minimumCardHeight(display, previewCard.kind)) }); }

  async function createBoard() { const next = newWall(`Conspiracy Wall ${archive.walls.length + 1}`); await save({ ...archive, walls: [...archive.walls, next] }); setActive(next.id); }
  async function duplicateBoard() { const stamp = now(); const regionIds = new Map(wall.regions.map((region) => [region.id, crypto.randomUUID()])); const homeIds = new Map(wall.cards.filter((card) => card.kind === 'home').map((card) => [card.id, crypto.randomUUID()])); const next: WallRecord = { ...structuredClone(wall), id: crypto.randomUUID(), title: `${wall.title} Copy`, createdAt: stamp, updatedAt: stamp, regions: wall.regions.map((region) => ({ ...region, id: regionIds.get(region.id)!, createdAt: stamp, updatedAt: stamp })), cards: wall.cards.map((card) => ({ ...card, id: card.kind === 'home' ? homeIds.get(card.id)! : crypto.randomUUID(), homeCardId: card.homeCardId ? homeIds.get(card.homeCardId) : undefined, regionId: card.regionId ? regionIds.get(card.regionId) : undefined, createdAt: stamp, updatedAt: stamp })) }; await save({ ...archive, walls: [...archive.walls, next] }); setActive(next.id); }
  async function deleteBoard() { if (!archive.walls.some((item) => item.id === wall.id) || !window.confirm(`Delete “${wall.title}”?`)) return; const walls = archive.walls.filter((item) => item.id !== wall.id); await save({ ...archive, walls }); setActive(walls[0]?.id || ''); }
  async function addHome(type: WallSourceType, id: string) { const index = wall.cards.length; const stamp = now(); const card: WallCardRecord = { id: crypto.randomUUID(), sourceType: type, sourceId: id, kind: 'home', x: 70 + index % 5 * 250, y: 90 + Math.floor(index / 5) * 250, width: 236, height: 260, color: type === 'dossier' ? '#b96934' : type === 'theory' ? '#a65a31' : type === 'suspicion' ? '#96546f' : '#657c96', display: { ...DEFAULT_DISPLAY }, createdAt: stamp, updatedAt: stamp }; await saveWall({ ...wall, cards: [...wall.cards, card] }); setSearch(''); }
  async function removeCard(card: WallCardRecord) { const removed = new Set([card.id]); if (card.kind === 'home') wall.cards.filter((item) => item.homeCardId === card.id).forEach((item) => removed.add(item.id)); await saveWall({ ...wall, cards: wall.cards.filter((item) => !removed.has(item.id)) }); setPreviewId(null); }
  async function addAppearance(home: WallCardRecord, regionId: string) { const region = wall.regions.find((item) => item.id === regionId); if (!region || wall.cards.some((card) => card.kind === 'reference' && card.homeCardId === home.id && card.regionId === regionId)) return; const count = wall.cards.filter((card) => card.regionId === regionId).length; const stamp = now(); const card: WallCardRecord = { id: crypto.randomUUID(), sourceType: home.sourceType, sourceId: home.sourceId, kind: 'reference', homeCardId: home.id, regionId, x: region.x + 20 + count % 3 * 190, y: region.y + REGION_HEADER + 18 + Math.floor(count / 3) * 145, width: 190, height: 138, color: home.color, display: { ...DEFAULT_DISPLAY, density: 'minimal', showSummary: false, showStatus: false }, createdAt: stamp, updatedAt: stamp }; await saveWall({ ...wall, cards: [...wall.cards, card] }); setAppearanceRegion(''); }
  async function addToWall(home: WallCardRecord, wallId: string) { const target = archive.walls.find((item) => item.id === wallId); if (!target || target.cards.some((card) => card.kind === 'home' && card.sourceType === home.sourceType && card.sourceId === home.sourceId)) return; const stamp = now(); const card: WallCardRecord = { ...home, id: crypto.randomUUID(), homeCardId: undefined, kind: 'home', regionId: undefined, x: 80, y: 80, createdAt: stamp, updatedAt: stamp }; await save({ ...archive, walls: archive.walls.map((item) => item.id === target.id ? { ...item, cards: [...item.cards, card], updatedAt: stamp } : item) }); setTargetWallId(''); }

  async function createDossier(event: React.FormEvent) { event.preventDefault(); if (!draft.title.trim()) return; const stamp = now(); const dossier: WallDossierRecord = { id: crypto.randomUUID(), category: draft.category, title: draft.title.trim(), shortSummary: draft.shortSummary.trim(), overview: draft.overview.trim(), notes: draft.notes.trim() || undefined, bookIds: draft.bookIds, theoryIds: draft.theoryIds, suspicionIds: draft.suspicionIds, dossierIds: draft.dossierIds, createdAt: stamp, updatedAt: stamp }; const nextArchive = { ...archive, dossiers: [...archive.dossiers, dossier] }; const card: WallCardRecord = { id: crypto.randomUUID(), sourceType: 'dossier', sourceId: dossier.id, kind: 'home', x: 70 + wall.cards.length % 5 * 250, y: 90 + Math.floor(wall.cards.length / 5) * 280, width: 236, height: 260, color: '#b96934', display: { ...DEFAULT_DISPLAY }, createdAt: stamp, updatedAt: stamp }; const nextWall = { ...wall, cards: [...wall.cards, card], updatedAt: stamp }; const walls = archive.walls.some((item) => item.id === wall.id) ? archive.walls.map((item) => item.id === wall.id ? nextWall : item) : [...archive.walls, nextWall]; await save({ ...nextArchive, walls }); setDraft({ category: 'character', title: '', shortSummary: '', overview: '', notes: '', bookIds: [], theoryIds: [], suspicionIds: [], dossierIds: [] }); setShowDossierForm(false); }

  async function saveProfile() {
    if (!previewSource) return;
    const stamp = now();
    let next = archive;
    if (previewSource.type === 'dossier') next = { ...next, dossiers: archive.dossiers.map((item) => item.id === previewSource.id ? { ...item, title: profileDraft.title.trim() || item.title, shortSummary: profileDraft.shortSummary.trim(), overview: profileDraft.overview.trim(), notes: profileDraft.notes.trim() || undefined, bookIds: profileDraft.bookIds, theoryIds: profileDraft.theoryIds, suspicionIds: profileDraft.suspicionIds, dossierIds: profileDraft.dossierIds.filter((id) => id !== item.id), updatedAt: stamp } : item) };
    if (previewSource.type === 'book') next = { ...next, books: archive.books.map((item) => item.id === previewSource.id ? { ...item, title: profileDraft.title.trim() || item.title, summary: profileDraft.shortSummary.trim(), about: profileDraft.overview.trim(), status: profileDraft.status as V2BookRecord['status'], theoryIds: profileDraft.theoryIds, suspicionIds: profileDraft.suspicionIds, updatedAt: stamp } : item) };
    if (previewSource.type === 'theory') next = { ...next, theories: archive.theories.map((item) => item.id === previewSource.id ? { ...item, title: profileDraft.title.trim() || item.title, statement: profileDraft.overview.trim() || profileDraft.shortSummary.trim(), status: profileDraft.status as TheoryRecord['status'], confidence: clamp(profileDraft.confidence, 0, 100), bookIds: profileDraft.bookIds, updatedAt: stamp } : item) };
    if (previewSource.type === 'suspicion') next = { ...next, suspicions: archive.suspicions.map((item) => item.id === previewSource.id ? { ...item, title: profileDraft.title.trim() || item.title, details: profileDraft.overview.trim() || profileDraft.shortSummary.trim(), status: profileDraft.status as SuspicionRecord['status'], confidence: clamp(profileDraft.confidence, 0, 100), bookIds: profileDraft.bookIds, updatedAt: stamp } : item) };
    await save(next);
    setEditingProfile(false);
  }

  async function addRegion() { const index = wall.regions.length; const stamp = now(); const region: WallRegionRecord = { id: crypto.randomUUID(), title: `Region ${index + 1}`, description: '', x: 50 + index % 2 * 620, y: 50 + Math.floor(index / 2) * 450, width: 570, height: 390, color: '#76567f', rule: 'manual', autoSort: false, collapsed: false, locked: false, layout: 'free', sort: 'manual', createdAt: stamp, updatedAt: stamp }; await saveWall({ ...wall, regions: [...wall.regions, region] }); setRegionSettingsId(region.id); }
  async function updateRegion(id: string, changes: Partial<WallRegionRecord>) { await saveWall({ ...wall, regions: wall.regions.map((region) => region.id === id ? { ...region, ...changes, updatedAt: now() } : region) }); }
  async function removeRegion(id: string) { await saveWall({ ...wall, regions: wall.regions.filter((region) => region.id !== id), cards: wall.cards.map((card) => card.regionId === id ? { ...card, regionId: undefined } : card) }); setRegionSettingsId(null); }
  function regionAt(x: number, y: number, width: number, height: number) { const cx = x + width / 2; const cy = y + height / 2; return wall.regions.find((region) => cx >= region.x && cx <= region.x + region.width && cy >= region.y + REGION_HEADER && cy <= region.y + region.height); }
  function begin(event: React.PointerEvent<HTMLElement>, value: Interaction) { const target = event.target as HTMLElement; if (target.closest('button,input,textarea,select') && !target.closest('.wall-resize-handle')) return; moved.current = false; event.currentTarget.setPointerCapture(event.pointerId); interaction.current = value; }
  function move(event: React.PointerEvent<HTMLElement>) { const current = interaction.current; if (!current) return; const dx = (event.clientX - current.startX) / zoom; const dy = (event.clientY - current.startY) / zoom; if (Math.abs(dx) > 2 || Math.abs(dy) > 2) moved.current = true; const element = event.currentTarget as HTMLElement; if (current.kind === 'card' || current.kind === 'region') { element.style.left = `${Math.max(0, current.x + dx)}px`; element.style.top = `${Math.max(0, current.y + dy)}px`; if (current.kind === 'region') current.children.forEach((child) => { const node = document.querySelector<HTMLElement>(`[data-wall-card-id="${child.id}"]`); if (node) { node.style.left = `${Math.max(0, child.x + dx)}px`; node.style.top = `${Math.max(0, child.y + dy)}px`; } }); } else { element.style.width = `${Math.max(current.kind === 'card-resize' ? 160 : 260, current.width + dx)}px`; element.style.height = `${Math.max(current.kind === 'card-resize' ? 110 : 220, current.height + dy)}px`; } }
  function end(event: React.PointerEvent<HTMLElement>) { const current = interaction.current; if (!current) return; interaction.current = null; const dx = (event.clientX - current.startX) / zoom; const dy = (event.clientY - current.startY) / zoom; if (current.kind === 'card') { const card = wall.cards.find((item) => item.id === current.id); if (!card) return; const x = Math.max(0, Math.round(current.x + dx)); const y = Math.max(0, Math.round(current.y + dy)); const region = regionAt(x, y, card.width, card.height); saveWall({ ...wall, cards: wall.cards.map((item) => item.id === card.id ? { ...item, x, y, regionId: region?.id, updatedAt: now() } : item) }).catch(console.error); } if (current.kind === 'card-resize') { const card = wall.cards.find((item) => item.id === current.id); if (!card) return; const display = displayFor(card); saveWall({ ...wall, cards: wall.cards.map((item) => item.id === current.id ? { ...item, width: Math.max(160, Math.round(current.width + dx)), height: Math.max(minimumCardHeight(display, item.kind), Math.round(current.height + dy)), updatedAt: now() } : item) }).catch(console.error); } if (current.kind === 'region') { const x = Math.max(0, Math.round(current.x + dx)); const y = Math.max(0, Math.round(current.y + dy)); saveWall({ ...wall, regions: wall.regions.map((region) => region.id === current.id ? { ...region, x, y, updatedAt: now() } : region), cards: wall.cards.map((card) => { const child = current.children.find((item) => item.id === card.id); return child ? { ...card, x: Math.max(0, Math.round(child.x + dx)), y: Math.max(0, Math.round(child.y + dy)), updatedAt: now() } : card; }) }).catch(console.error); } if (current.kind === 'region-resize') updateRegion(current.id, { width: Math.max(260, Math.round(current.width + dx)), height: Math.max(220, Math.round(current.height + dy)) }).catch(console.error); }
  function linkCounts(source: Source, home?: WallCardRecord) { const appearances = home ? wall.cards.filter((card) => card.homeCardId === home.id).length : 0; const regions = new Set(wall.cards.filter((card) => card.sourceType === source.type && card.sourceId === source.id && card.regionId).map((card) => card.regionId)).size; return { books: source.bookIds.length, theories: source.theoryIds.length, suspicions: source.suspicionIds.length, dossiers: source.dossierIds.length, appearances, regions }; }
  function fitBoard() { const node = viewport.current; if (!node) return; changeZoom(Math.min(1, (node.clientWidth - 30) / wall.canvasWidth, (node.clientHeight - 30) / wall.canvasHeight)); node.scrollTo({ left: 0, top: 0, behavior: 'smooth' }); }

  return <div className={`wall-module${previewCard ? ' has-profile-drawer' : ''}`}>
    <header className="wall-main-header"><div><p>Investigation Board</p><h2>Conspiracy Wall</h2><span>{plural(wall.cards.filter((card) => card.kind === 'home').length, 'dossier')} · {plural(wall.cards.filter((card) => card.kind === 'reference').length, 'appearance')} · {plural(wall.regions.length, 'region')}</span></div><div className="wall-header-actions"><button onClick={() => setShowDossierForm(true)}>+ Dossier</button><button onClick={createBoard}>+ Board</button><button className="wall-icon-button" onClick={() => setShowBoardMenu((value) => !value)}>☰</button>{showBoardMenu && <div className="wall-popover"><button onClick={duplicateBoard}>Duplicate board</button><button className="is-danger" onClick={deleteBoard}>Delete board</button></div>}</div></header>
    <section className="wall-compact-toolbar"><label><span>Wall</span><select value={wall.id} onChange={(event) => setActive(event.target.value)}>{archive.walls.length ? archive.walls.map((item) => <option key={item.id} value={item.id}>{item.title}</option>) : <option value={wall.id}>{wall.title}</option>}</select></label><div className="wall-toolbar-actions"><button onClick={addRegion}>+ Region</button><button onClick={() => setShowFilters((value) => !value)}>⌕ Filters</button><div className="wall-zoom-group"><button onClick={() => changeZoom(zoom - .1)}>−</button><strong>{Math.round(zoom * 100)}%</strong><button onClick={() => changeZoom(zoom + .1)}>+</button><button onClick={fitBoard}>Fit</button></div></div></section>
    {showFilters && <section className="wall-filter-drawer"><select value={filterType} onChange={(event) => setFilterType(event.target.value as typeof filterType)}><option value="all">All card types</option><option value="book">Books</option><option value="theory">Theories</option><option value="suspicion">Suspicions</option><option value="dossier">Wall dossiers</option></select><select value={filterRegion} onChange={(event) => setFilterRegion(event.target.value)}><option value="all">All regions</option><option value="unassigned">Unassigned</option>{wall.regions.map((region) => <option key={region.id} value={region.id}>{region.title}</option>)}</select><button onClick={() => { setFilterType('all'); setFilterRegion('all'); }}>Clear</button></section>}
    <section className="wall-add-source"><label>Add an existing record<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search books, theories, suspicions, or dossiers…" /></label>{search && <div className="wall-source-results">{available.length ? available.map((source) => <button key={`${source.type}-${source.id}`} onClick={() => addHome(source.type, source.id)}><strong>{source.title}</strong><span>{source.category} · {source.shortSummary}</span></button>) : <p>No new records match.</p>}</div>}</section>
    <div className="wall-viewport" ref={viewport} onWheel={(event) => { if (!event.ctrlKey && !event.metaKey) return; event.preventDefault(); changeZoom(zoom + (event.deltaY < 0 ? .1 : -.1)); }}><div className="wall-zoom-surface" style={{ width: wall.canvasWidth * zoom, height: wall.canvasHeight * zoom }}><section className="wall-canvas" style={{ width: wall.canvasWidth, height: wall.canvasHeight, transform: `scale(${zoom})`, transformOrigin: 'top left' }}>
      {wall.regions.map((region) => { const children = wall.cards.filter((card) => card.regionId === region.id); return <article key={region.id} className={`wall-region${region.collapsed ? ' is-collapsed' : ''}`} style={{ left: region.x, top: region.y, width: region.width, height: region.collapsed ? REGION_HEADER : region.height, borderColor: region.color, backgroundColor: alpha(region.color, '12') }} onPointerDown={(event) => { if (!region.locked) begin(event, { kind: 'region', id: region.id, startX: event.clientX, startY: event.clientY, x: region.x, y: region.y, children: children.map((card) => ({ id: card.id, x: card.x, y: card.y })) }); }} onPointerMove={move} onPointerUp={end}><header><div><strong>{region.title}</strong><span>{region.description || plural(children.length, 'placement')}</span></div><nav><button onClick={() => updateRegion(region.id, { collapsed: !region.collapsed })}>{region.collapsed ? 'Expand' : 'Collapse'}</button><button onClick={() => setRegionSettingsId(region.id)}>•••</button></nav></header>{!region.collapsed && !region.locked && <button className="wall-resize-handle" onPointerDown={(event) => { event.stopPropagation(); begin(event, { kind: 'region-resize', id: region.id, startX: event.clientX, startY: event.clientY, width: region.width, height: region.height }); }} onPointerMove={move} onPointerUp={end} />}</article>; })}
      {wall.cards.map((card) => { const source = sourceFor(card); const home = homeFor(card); const region = card.regionId ? wall.regions.find((item) => item.id === card.regionId) : undefined; if (!source || region?.collapsed || !visibleIds.has(card.id)) return null; const counts = linkCounts(source, home); const color = card.color || '#a64f24'; const display = displayFor(card); const footerBits = [counts.books && plural(counts.books, 'book'), counts.theories && plural(counts.theories, 'theory'), counts.suspicions && plural(counts.suspicions, 'suspicion'), counts.dossiers && plural(counts.dossiers, 'dossier'), counts.regions && plural(counts.regions, 'region'), counts.appearances && plural(counts.appearances, 'appearance')].filter(Boolean); return <article key={card.id} data-wall-card-id={card.id} className={`wall-card wall-dossier-card is-${card.kind} density-${display.density}`} style={{ left: card.x, top: card.y, width: card.width, height: card.height, borderColor: color, background: `linear-gradient(145deg, ${alpha(color, card.kind === 'reference' ? '18' : '25')}, rgba(26,16,11,.98))`, boxShadow: `0 0 0 3px ${alpha(color, '44')}` }} onClick={() => { if (!moved.current) setPreviewId(card.id); }} onPointerDown={(event) => begin(event, { kind: 'card', id: card.id, startX: event.clientX, startY: event.clientY, x: card.x, y: card.y })} onPointerMove={move} onPointerUp={end}>
        <header>{display.showCategory ? <span className={`wall-card-category is-${display.categoryStyle}`}>{card.kind === 'reference' ? 'Linked appearance' : source.category}</span> : <span />}<button onClick={(event) => { event.stopPropagation(); removeCard(card); }}>×</button></header><h3>{source.title}</h3>{display.showSummary && <div className="wall-card-summary-block"><span>Summary</span><p>{source.shortSummary}</p></div>}{display.showCounts && <footer className={`wall-card-connection-footer is-${display.countsStyle}`}>{footerBits.length ? footerBits.map((bit) => <span key={String(bit)}>{bit}</span>) : <span>0 connections</span>}</footer>}{display.showStatus && <div className="wall-card-status">{source.status || 'Active record'}</div>}<button className="wall-resize-handle" onPointerDown={(event) => { event.stopPropagation(); begin(event, { kind: 'card-resize', id: card.id, startX: event.clientX, startY: event.clientY, width: card.width, height: card.height }); }} onPointerMove={move} onPointerUp={end} /></article>; })}
      {!wall.cards.length && <div className="wall-empty"><span>✣</span><h3>No dossiers pinned yet</h3><p>Create a wall-native dossier or search existing records above.</p></div>}
    </section></div></div>

    {showDossierForm && <div className="wall-modal-backdrop"><form className="wall-settings-modal wall-dossier-editor" onSubmit={createDossier}><header><div><p>Wall-native Record</p><h3>Create Dossier</h3></div><button type="button" onClick={() => setShowDossierForm(false)}>×</button></header><div className="wall-settings-grid"><label>Category<select value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value as WallDossierCategory })}>{CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label>Title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} required /></label><label className="is-wide">One-sentence summary<input value={draft.shortSummary} onChange={(event) => setDraft({ ...draft, shortSummary: event.target.value })} /></label><label className="is-wide">Overview<textarea rows={6} value={draft.overview} onChange={(event) => setDraft({ ...draft, overview: event.target.value })} /></label><label className="is-wide">Notes & lore<textarea rows={4} value={draft.notes} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} /></label><label>Linked books<select multiple value={draft.bookIds} onChange={(event) => setDraft({ ...draft, bookIds: selectedValues(event) })}>{archive.books.map((book) => <option key={book.id} value={book.id}>{book.title}</option>)}</select></label><label>Linked theories<select multiple value={draft.theoryIds} onChange={(event) => setDraft({ ...draft, theoryIds: selectedValues(event) })}>{archive.theories.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Linked suspicions<select multiple value={draft.suspicionIds} onChange={(event) => setDraft({ ...draft, suspicionIds: selectedValues(event) })}>{archive.suspicions.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Linked dossiers<select multiple value={draft.dossierIds} onChange={(event) => setDraft({ ...draft, dossierIds: selectedValues(event) })}>{archive.dossiers.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label></div><footer><button type="button" onClick={() => setShowDossierForm(false)}>Cancel</button><button className="is-primary">Create & Pin</button></footer></form></div>}

    {regionSettings && <div className="wall-modal-backdrop"><section className="wall-settings-modal"><header><div><p>Canvas Region</p><h3>Region Settings</h3></div><button onClick={() => setRegionSettingsId(null)}>×</button></header><div className="wall-settings-grid"><label>Name<input value={regionSettings.title} onChange={(event) => updateRegion(regionSettings.id, { title: event.target.value })} /></label><label>Color<input type="color" value={regionSettings.color} onChange={(event) => updateRegion(regionSettings.id, { color: event.target.value })} /></label><label className="is-wide">Description<textarea rows={3} value={regionSettings.description || ''} onChange={(event) => updateRegion(regionSettings.id, { description: event.target.value })} /></label><label>Assignment<select value={regionSettings.rule} onChange={(event) => updateRegion(regionSettings.id, { rule: event.target.value as WallRegionRule })}>{RULES.map((rule) => <option key={rule.value} value={rule.value}>{rule.label}</option>)}</select></label><label className="wall-check"><input type="checkbox" checked={Boolean(regionSettings.locked)} onChange={(event) => updateRegion(regionSettings.id, { locked: event.target.checked })} />Lock region</label></div><footer><button onClick={() => updateRegion(regionSettings.id, { collapsed: !regionSettings.collapsed })}>{regionSettings.collapsed ? 'Expand' : 'Collapse'}</button><button className="is-danger" onClick={() => removeRegion(regionSettings.id)}>Delete Region</button><button className="is-primary" onClick={() => setRegionSettingsId(null)}>Done</button></footer></section></div>}

    {previewCard && previewHome && previewSource && <aside className="wall-profile-drawer wall-old-dossier-profile" aria-label={`${previewSource.title} profile`}><header className="wall-dossier-hero" style={{ borderTopColor: previewCard.color || '#a64f24' }}><div className="wall-dossier-avatar">{previewSource.title.slice(0, 1).toUpperCase()}</div><div className="wall-dossier-identity"><p>{previewSource.category} Record</p><h3>{previewSource.title}</h3><div className="wall-dossier-badges"><span>{plural(previewSource.bookIds.length, 'book')}</span><span>{wall.title}</span></div></div><div className="wall-dossier-header-actions"><button onClick={() => setEditingProfile((value) => !value)}>{editingProfile ? 'Cancel' : 'Edit record'}</button><button className="wall-modal-close" onClick={() => setPreviewId(null)}>×</button></div></header><div className="wall-profile-scroll">
      {editingProfile && <section className="wall-profile-editor compact"><h4>Edit record</h4><label>Title<input value={profileDraft.title} onChange={(event) => setProfileDraft({ ...profileDraft, title: event.target.value })} /></label><label>One-sentence summary<input value={profileDraft.shortSummary} onChange={(event) => setProfileDraft({ ...profileDraft, shortSummary: event.target.value })} /></label><label>Overview<textarea rows={5} value={profileDraft.overview} onChange={(event) => setProfileDraft({ ...profileDraft, overview: event.target.value })} /></label>{previewSource.type === 'dossier' && <label>Notes & lore<textarea rows={4} value={profileDraft.notes} onChange={(event) => setProfileDraft({ ...profileDraft, notes: event.target.value })} /></label>}{previewSource.type !== 'dossier' && <label>Status<input value={profileDraft.status} onChange={(event) => setProfileDraft({ ...profileDraft, status: event.target.value })} /></label>}{(previewSource.type === 'theory' || previewSource.type === 'suspicion') && <label>Confidence<input type="number" min="0" max="100" value={profileDraft.confidence} onChange={(event) => setProfileDraft({ ...profileDraft, confidence: Number(event.target.value) })} /></label>}<div className="wall-profile-connection-grid"><label>Books<select multiple value={profileDraft.bookIds} onChange={(event) => setProfileDraft({ ...profileDraft, bookIds: selectedValues(event) })}>{archive.books.map((book) => <option key={book.id} value={book.id}>{book.title}</option>)}</select></label><label>Theories<select multiple value={profileDraft.theoryIds} onChange={(event) => setProfileDraft({ ...profileDraft, theoryIds: selectedValues(event) })}>{archive.theories.filter((item) => !(previewSource.type === 'theory' && item.id === previewSource.id)).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Suspicions<select multiple value={profileDraft.suspicionIds} onChange={(event) => setProfileDraft({ ...profileDraft, suspicionIds: selectedValues(event) })}>{archive.suspicions.filter((item) => !(previewSource.type === 'suspicion' && item.id === previewSource.id)).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Dossiers<select multiple value={profileDraft.dossierIds} onChange={(event) => setProfileDraft({ ...profileDraft, dossierIds: selectedValues(event) })}>{archive.dossiers.filter((item) => !(previewSource.type === 'dossier' && item.id === previewSource.id)).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label></div><button className="is-primary" onClick={saveProfile}>Save record</button></section>}
      <section className="wall-profile-collapsible"><button className="wall-profile-section-toggle" onClick={() => setOverviewOpen((value) => !value)}><span>Overview</span><span>{overviewOpen ? '−' : '+'}</span></button>{overviewOpen && <div className="wall-profile-section-content"><p className={previewSource.overview ? '' : 'is-empty'}>{previewSource.overview || 'Add an overview when you are ready.'}</p>{previewSource.notes && <><h5>Notes & lore</h5><p>{previewSource.notes}</p></>}</div>}</section>
      <section className="wall-profile-collapsible"><button className="wall-profile-section-toggle" onClick={() => setConnectionsOpen((value) => !value)}><span>Connections</span><span>{connectionsOpen ? '−' : '+'}</span></button>{connectionsOpen && <div className="wall-profile-section-content"><div className="wall-link-groups">{previewSource.bookIds.length > 0 && <div><strong>Books</strong>{previewSource.bookIds.map((id) => <span key={id}>{archive.books.find((book) => book.id === id)?.title || 'Missing book'}</span>)}</div>}{previewSource.theoryIds.length > 0 && <div><strong>Theories</strong>{previewSource.theoryIds.map((id) => <span key={id}>{archive.theories.find((item) => item.id === id)?.title || 'Missing theory'}</span>)}</div>}{previewSource.suspicionIds.length > 0 && <div><strong>Suspicions</strong>{previewSource.suspicionIds.map((id) => <span key={id}>{archive.suspicions.find((item) => item.id === id)?.title || 'Missing suspicion'}</span>)}</div>}{previewSource.dossierIds.length > 0 && <div><strong>Other dossiers</strong>{previewSource.dossierIds.map((id) => <button key={id} onClick={() => { const target = wall.cards.find((card) => card.kind === 'home' && card.sourceType === 'dossier' && card.sourceId === id); if (target) setPreviewId(target.id); }}>{archive.dossiers.find((item) => item.id === id)?.title || 'Missing dossier'}</button>)}</div>}{!previewSource.bookIds.length && !previewSource.theoryIds.length && !previewSource.suspicionIds.length && !previewSource.dossierIds.length && <p className="is-empty">No connections yet.</p>}</div></div>}</section>
      <section className="wall-profile-collapsible"><button className="wall-profile-section-toggle" onClick={() => setPlacementsOpen((value) => !value)}><span>Where this dossier appears</span><span>{placementsOpen ? '−' : '+'}</span></button>{placementsOpen && <div className="wall-profile-section-content"><div className="wall-add-appearance"><select value={appearanceRegion} onChange={(event) => setAppearanceRegion(event.target.value)}><option value="">Add a linked appearance to a region…</option>{wall.regions.filter((region) => region.id !== previewHome.regionId && !wall.cards.some((card) => card.kind === 'reference' && card.homeCardId === previewHome.id && card.regionId === region.id)).map((region) => <option key={region.id} value={region.id}>{region.title}</option>)}</select><button disabled={!appearanceRegion} onClick={() => addAppearance(previewHome, appearanceRegion)}>Add</button></div><div className="wall-add-appearance"><select value={targetWallId} onChange={(event) => setTargetWallId(event.target.value)}><option value="">Add to another wall…</option>{archive.walls.filter((item) => item.id !== wall.id && !item.cards.some((card) => card.kind === 'home' && card.sourceType === previewHome.sourceType && card.sourceId === previewHome.sourceId)).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><button disabled={!targetWallId} onClick={() => addToWall(previewHome, targetWallId)}>Add</button></div></div>}</section>
      <section className="wall-profile-collapsible"><button className="wall-profile-section-toggle" onClick={() => setDisplayOpen((value) => !value)}><span>Card display</span><span>{displayOpen ? '−' : '+'}</span></button>{displayOpen && <div className="wall-profile-section-content wall-card-display-settings compact"><label>Card color<input type="color" value={previewCard.color || '#a64f24'} onChange={(event) => updateCard(previewCard.id, { color: event.target.value })} /></label><div className="wall-display-toggles"><label><input type="checkbox" checked={previewDisplay.showCategory} onChange={(event) => updateDisplay({ showCategory: event.target.checked })} />Category</label><label><input type="checkbox" checked={previewDisplay.showSummary} onChange={(event) => updateDisplay({ showSummary: event.target.checked })} />One-sentence summary</label><label><input type="checkbox" checked={previewDisplay.showCounts} onChange={(event) => updateDisplay({ showCounts: event.target.checked })} />Connections footer</label><label><input type="checkbox" checked={previewDisplay.showStatus} onChange={(event) => updateDisplay({ showStatus: event.target.checked })} />Status</label></div></div>}</section>
      {previewSource.confidence != null && <section className="wall-profile-confidence"><h4>Confidence</h4><div className="wall-confidence"><span style={{ width: `${previewSource.confidence}%` }} /><strong>{previewSource.confidence}%</strong></div></section>}
    </div><footer><button onClick={() => { const node = viewport.current; node?.scrollTo({ left: Math.max(0, previewHome.x * zoom - 100), top: Math.max(0, previewHome.y * zoom - 100), behavior: 'smooth' }); }}>Jump to home</button><button className="is-primary" onClick={() => setPreviewId(null)}>Close</button></footer></aside>}
  </div>;
}
