import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { loadCloudArchive, saveCloudArchive, saveLocalArchive, type V2ArchiveState } from './archive';
import { PATHS, rankIndexForPoints, type PathId } from './paths';
import { getAuthSnapshot } from './supabase';
import './rank-story-runtime.css';

type Creature = { kind:'dragon'|'gryphon'|'wyvern'; name:string; color:string; tail?:string; flameColor?:string; strength?:number };
type StoryRecord = { key:string; title:string; rank:string; story:string; completedAt:string; answers:string[] };
type Progression = { completedEvents?:string[]; stories?:StoryRecord[]; creatureRevealed?:boolean; abilityRevealed?:boolean; riderUnit?:{wing:number;section:'Flame'|'Claw'|'Tail';squad:1|2|3}; flierServiceWing?:'Summit Wing'|'Nightwing Drift'|'Seawing Drift' };
type Profile = V2ArchiveState['profile'] & { abilityName?:string; abilityDescription?:string; creature?:Creature; progression?:Progression };

type Question = { prompt:string; choices:string[] };
const COMMON: Record<PathId, Question[]> = {
  rider:[{prompt:'A squadmate freezes while danger closes in. What do you do?',choices:['Put yourself between them and the threat.','Give one clear order and trust them to move.','Break formation and create a new opening.']},{prompt:'An order will save the mission but cost someone dearly. What matters most?',choices:['No victory is worth abandoning your people.','The mission survives only if someone decides.','Find the flaw in the choice and make another path.']},{prompt:'What earns your loyalty?',choices:['Courage under pressure.','Consistency when no one is watching.','A mind strong enough to challenge mine.']}],
  gryphon:[{prompt:'A border patrol discovers civilians trapped between two forces. What do you do?',choices:['Land and pull them out yourself.','Draw the enemy away through the clouds.','Refuse the official route and open a safer corridor.']},{prompt:'Your drift disagrees with command. How do you respond?',choices:['Speak openly and accept the consequences.','Build consensus before the next flight.','Obey only the part that protects your people.']},{prompt:'What makes a flier worth following?',choices:['Defiance with purpose.','Calm judgment in the air.','Loyalty that survives disagreement.']}],
  dark:[{prompt:'The source offers more power than you can safely hold. What do you do?',choices:['Take only what you can control.','Take everything and pay the price later.','Feed part of it into your wyvern instead.']},{prompt:'A rival senses weakness. How do you answer?',choices:['Let them come closer.','Strike before they finish deciding.','Make them fear what they cannot see.']},{prompt:'What does ascension require?',choices:['Control.','Hunger.','Transformation.']}],
  scribe:[{prompt:'Two records contradict each other. Which do you trust first?',choices:['The account with the strongest evidence.','The witness with the most to lose.','Neither, until the missing context is found.']},{prompt:'A dangerous truth could destabilize the archive. What do you do?',choices:['Preserve it exactly.','Restrict it until the risk is understood.','Release it with every source attached.']},{prompt:'What makes a record worthy?',choices:['Accuracy.','Context.','The courage to preserve what power dislikes.']}],
  infantry:[{prompt:'Your unit is exhausted and the objective is still ahead. What do you do?',choices:['Shorten the line and keep moving.','Call a halt before discipline collapses.','Take the hardest position yourself.']},{prompt:'A new recruit makes a costly mistake. How do you respond?',choices:['Correct them privately and rebuild confidence.','Make the lesson visible so it is not repeated.','Pair them with someone steady and continue.']},{prompt:'What wins a long campaign?',choices:['Endurance.','Discipline.','People who refuse to leave each other behind.']}],
  healer:[{prompt:'Two patients need you at once. How do you decide?',choices:['Treat the most immediate threat first.','Stabilize both before committing.','Call for help and refuse the false choice.']},{prompt:'A patient hides symptoms out of fear. What do you do?',choices:['Create enough safety for the truth to surface.','Explain the cost of withholding information.','Observe until the pattern reveals what they cannot say.']},{prompt:'What does healing require most?',choices:['Compassion.','Precision.','The patience to understand the whole wound.']}]
};

function eventTitle(path:PathId, rank:number){if(path==='rider'&&rank===1)return'Threshing';if(path==='gryphon'&&rank===1)return'The Harvest';if(path==='rider'&&rank===2)return'First Channeling';if(path==='gryphon'&&rank===2)return'Mindwork Awakening';return `${PATHS[path].ranks[rank]} Trial`;}
function buildStory(path:PathId, rank:number, profile:Profile, answers:string[]){const creature=profile.creature;const rankName=PATHS[path].ranks[rank];if(path==='rider'&&rank===1&&creature){return `You entered Threshing already knowing where you belonged: ${profile.progression?.riderUnit?.wing} Wing, ${profile.progression?.riderUnit?.section} Section, Squad ${profile.progression?.riderUnit?.squad}. Then ${creature.name}, a ${creature.color.toLowerCase()} dragon with a ${creature.tail}, watched every choice you made. It chose you because you did not confuse bravery with spectacle.`;}if(path==='gryphon'&&rank===1&&creature){return `You entered The Harvest carrying the colors of ${profile.progression?.flierServiceWing}. When the wind broke formation, ${creature.name} descended through the crosscurrent, its ${creature.color.toLowerCase()} coloring blending the natural tones of fur and feather. It chose you because your defiance still made room for responsibility.`;}if(path==='dark'&&rank===1&&creature){return `The source pressed against every weakness you carried. Your grey wyvern, ${creature.name}, answered with ${String(creature.flameColor||'blue').toLowerCase()} fire. You did not emerge unchanged. You emerged recognized.`;}return `Your choices at the ${rankName} threshold became part of your permanent record. You chose ${answers[0].toLowerCase()}, then proved that choice when the cost became real. By the end of the trial, your path had stopped being an assignment and become a story only you could have written.`;}

function App(){const[archive,setArchive]=useState<V2ArchiveState|null>(null);const[answers,setAnswers]=useState<string[]>([]);const[step,setStep]=useState(0);const[done,setDone]=useState(false);const[story,setStory]=useState('');
useEffect(()=>{getAuthSnapshot().then(async({user})=>{if(user)setArchive(await loadCloudArchive(user));});},[]);
const profile=archive?.profile as Profile|undefined;const path=(profile?.path||'rider') as PathId;const rank=profile?rankIndexForPoints(path,profile.points||0):0;const key=`${path}:${rank}`;const completed=profile?.progression?.completedEvents||[];const eligible=Boolean(profile?.onboarded&&rank>0&&!completed.includes(key));const questions=COMMON[path];const title=eventTitle(path,rank);
if(!archive||!eligible)return null;
async function choose(choice:string){const next=[...answers,choice];if(step<2){setAnswers(next);setStep(step+1);return;}const nextStory=buildStory(path,rank,profile!,next);const progression:Progression={...(profile!.progression||{}),completedEvents:[...completed,key],stories:[...(profile!.progression?.stories||[]),{key,title,rank:PATHS[path].ranks[rank],story:nextStory,completedAt:new Date().toISOString(),answers:next}],...(path==='rider'&&rank===1?{creatureRevealed:true}:{}),...(path==='gryphon'&&rank===1?{creatureRevealed:true}:{}),...((path==='rider'||path==='gryphon')&&rank===2?{abilityRevealed:true}:{})};const nextArchive={...archive,profile:{...profile!,progression},updatedAt:new Date().toISOString()};setStory(nextStory);setDone(true);setArchive(nextArchive);saveLocalArchive(nextArchive);const{user}=await getAuthSnapshot();if(user)await saveCloudArchive(user,nextArchive);}
return <div className="rank-story-backdrop"><section className="rank-story-card">{!done?<><p>{PATHS[path].short}</p><h1>{title}</h1><small>{PATHS[path].ranks[rank]} threshold</small><h2>{questions[step].prompt}</h2><div>{questions[step].choices.map(c=><button key={c} onClick={()=>void choose(c)}>{c}</button>)}</div><footer>{step+1} / 3</footer></>:<><p>Chapter recorded</p><h1>{title}</h1><article>{story}</article>{path==='rider'&&rank===1&&profile?.creature&&<div className="rank-story-reveal"><strong>{profile.creature.name}</strong><span>{profile.creature.color} dragon · {profile.creature.tail}</span></div>}{path==='gryphon'&&rank===1&&profile?.creature&&<div className="rank-story-reveal"><strong>{profile.creature.name}</strong><span>{profile.creature.color} gryphon</span></div>}{(path==='rider'||path==='gryphon')&&rank===2&&profile?.abilityName&&<div className="rank-story-reveal"><strong>{profile.abilityName}</strong><span>{profile.abilityDescription}</span></div>}<button onClick={()=>location.reload()}>Continue your story</button></>}</section></div>}
function start(){const host=document.createElement('div');host.id='rank-story-runtime';document.body.appendChild(host);createRoot(host).render(<StrictMode><App/></StrictMode>)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();